#|
 This file is a part of Colleen
 (c) 2015 Shirakumo http://tymoon.eu (shinmera@tymoon.eu)
 Author: Nicolas Hafner <shinmera@tymoon.eu>
|#

(in-package #:org.shirakumo.colleen.clients.irc)

(deeds:define-event irc-event (client-event)
  ())

(deeds:define-event reply-event (irc-event)
  ((sender :initarg :sender :reader sender)
   (sender-user :initarg :sender-user :reader sender-user)
   (sender-host :initarg :sender-host :reader sender-host)
   (code :initarg :code)
   (args :initarg :args)))

(defmethod print-object ((reply-event reply-event) stream)
  (print-unreadable-object (reply-event stream :type T :identity T)
    (format stream "~s ~a" :sender (sender reply-event))))

(deeds:define-event unknown-event (reply-event)
  ())

(defvar *reply-events* (make-hash-table :test 'equalp))

(defun parse-reply (client message)
  (or
   (cl-ppcre:register-groups-bind (NIL sender NIL user NIL host code NIL args)
       ("^(:([^! ]+)(!([^@ ]+))?(@([^ ]+))? +)?([^ ]+)( +(.+))?$" message)
     (let ((events (or (gethash code *reply-events*)
                       (progn (warn 'unknown-message-event-warning :client client :message message)
                              '(unknown-event)))))
       (mapcar (lambda (event)
                 (make-instance event :client client :code code :args args
                                      :sender sender :sender-user user :sender-host host))
               events)))
   (error 'message-parse-error :client client :message message)))

(defmacro define-irc-reply (name code (regex &rest args))
  (let ((name (intern (string name) '#:org.shirakumo.colleen.clients.irc.events))
        (code (etypecase code
                (symbol (string code))
                (string code)
                (integer (format NIL "~3,'0d" code))))
        (instance (gensym "INSTANCE"))
        (rest (gensym "REST")))
    `(progn
       (deeds:define-event ,name (reply-event)
         ,(loop for arg in args
                for (name delim) = (ensure-list arg NIL)
                when name
                collect `(,name :initarg ,(kw name)))
         (:default-initargs :code ,code))
       (defmethod initialize-instance :around ((,instance ,name) &rest ,rest &key args)
         (if args
             (or (cl-ppcre:register-groups-bind ,(mapcar #'unlist args) (,regex args)
                   (apply #'call-next-method
                          ,instance
                          ,@(loop for arg in args
                                  for (name delim) = (ensure-list arg NIL)
                                  when name
                                  append `(,(kw name) ,(if delim `(cl-ppcre:split ,(string delim) ,name) name)))
                          ,rest))
                 (and ;; signal an error
                  (call-next-method)))
             (call-next-method)))
       (pushnew ',name (gethash ,code *reply-events*)))))

;; Parsed from https://www.alien.net.au/irc/irc2numerics.html
;; Manually edited to suit a more parseable format, and to
;; remove conflicting duplicates.
(eval-when (:compile-toplevel :load-toplevel :execute)
  (defparameter *reply-descriptors*
    '((PASS RPL-PASS "(.*)" (PASSWORD))
      (NICK RPL-NICK "([^ ]+)( (.*))?" (NICKNAME NIL HOPCOUNT))
      (USER RPL-USER "([^ ]+) ([^ ]+) ([^ ]+) :(.*)" (USERNAME HOSTNAME SERVERNAME REALNAME))
      (SERVER RPL-SERVER "([^ ]+) ([^ ]+) :(.*)" (SERVERNAME HOPCOUNT INFO))
      (OPER RPL-OPER "([^ ]+) ([^ ]+)" (USER PASSWORD))
      (QUIT RPL-QUIT "(:(.*))?" (NIL COMMENT))
      (SQUIT RPL-SQUIT "([^ ]+) :(.*)" (SERVER COMMENT))
      (JOIN RPL-JOIN "([^ ]+) ([^ ]+)" ((CHANNELS #\,) (PASSWORDS #\,)))
      (PART RPL-PART "([^ ]+)" ((CHANNELS #\,)))
      (MODE RPL-MODE "([^ ]+) ([^ ]+)( ([^ ]+)( ([^ ]+)( ([^ ]+))?)?)?" (TARGET MODE NIL LIMIT NIL USER NIL BAN-MASK))
      (TOPIC RPL-TOPIC "([^ ]+)( :(.*))?" (CHANNEL NIL TOPIC))
      (NAMES RPL-NAMES "([^ ]+)" ((CHANNELS #\,)))
      (LIST RPL-LIST "([^ ]+)( ([^ ]+))?" ((CHANNELS #\,) NIL SERVER))
      (INVITE RPL-INVITE "([^ ]+) ([^ ]+)" (NICKNAME CHANNEL))
      (KICK RPL-KICK "([^ ]+) ([^ ]+)( :(.*))?" (CHANNEL USER NIL COMMENT))
      (VERSION RPL-VERSION "([^ ]+)?" (SERVER))
      (STATS RPL-STATS "(([^ ]+)( ([^ ]+))?)?" (NIL QUERY NIL SERVER))
      (LINKS RPL-LINKS "((([^ ]+) )?([^ ]+))?" (NIL NIL REMOTE-SERVER SERVER-MASK))
      (TIME RPL-TIME "([^ ]+)?" (SERVER))
      (CONNECT RPL-CONNECT "(([^ ]+)( ([^ ]+)( ([^ ]+))?)?)?" (NIL TARGET NIL PORT NIL REMOTE))
      (TRACE RPL-TRACE "([^ ]+)?" (SERVER))
      (ADMIN RPL-ADMIN "([^ ]+)?" (SERVER))
      (INFO RPL-INFO "([^ ]+)?" (SERVER))
      (PRIVMSG RPL-PRIVMSG "([^ ]+) :(.*)" ((RECEIVERS #\,) MESSAGE))
      (NOTICE RPL-NOTICE "([^ ]+) ([^ ]+)" (NICKNAME TEXT))
      (WHO RPL-WHO "(([^ ]+)( o)?)?" (NIL NAME OPERS-ONLY))
      (WHOIS RPL-WHOIS "(([^ ]+) )?([^ ]+)" (NIL SERVER (NICKMASKS #\,)))
      (WHOWAS RPL-WHOWAS "([^ ]+)( ([^ ]+)( ([^ ]+))?)?" (NICKNAME NIL COUNT NIL SERVER))
      (KILL RPL-KILL "([^ ]+) :(.*)" (NICKNAME COMMENT))
      (PING RPL-PING "([^ ]+)( ([^ ]+))?" (SERVER NIL OTHER-SERVER))
      (PONG RPL-PONG "([^ ]+)( ([^ ]+))?" (DAEMON NIL OTHER-DAEMON))
      (ERROR RPL-ERROR ":(.*)" (MESSAGE))
      (AWAY RPL-AWAY "(:(.*))?" (NIL MESSAGE))
      (REHASH RPL-REHASH "" NIL)
      (RESTART RPL-RESTART "" NIL)
      (SUMMON RPL-SUMMON "([^ ]+)( ([^ ]+))?" (USER NIL SERVER))
      (USERS RPL-USERS "([^ ]+)?" (SERVER))
      (WALLOPS RPL-WALLOPS ":(.*)" (MESSAGE))
      (USERHOST RPL-USERHOST "(.*)" ((NICKNAMES #\ )))
      (ISON RPL-ISON "(.*)" ((NICKNAMES #\ )))
      (001 RPL-WELCOME "(:.*)" (INFO))
      (002 RPL-YOURHOST "(:.*)" (INFO))
      (003 RPL-CREATED "(:.*)" (INFO))
      (004 RPL-MYINFO "([^ ]+) ([^ ]+) ([^ ]+) ([^ ]+)" (SERVER-NAME VERSION USER-MODES CHAN-MODES))
      (005 RPL-BOUNCE "(:.*)" (INFO))
      (006 RPL-MAP "" NIL)
      (007 RPL-MAPEND "" NIL)
      (008 RPL-SNOMASK "" NIL)
      (009 RPL-STATMEMTOT "" NIL)
      (014 RPL-YOURCOOKIE "" NIL)
      (015 RPL-MAP "" NIL)
      (016 RPL-MAPMORE "" NIL)
      (017 RPL-MAPEND "" NIL)
      (042 RPL-YOURID "" NIL)
      (043 RPL-SAVENICK "(:.*)" (INFO))
      (050 RPL-ATTEMPTINGJUNC "" NIL)
      (051 RPL-ATTEMPTINGREROUTE "" NIL)
      (200 RPL-TRACELINK "Link
\([^(]+)(\\.([ ]+))? ([^
]+)
\([^ ]+) (V([^
]+)
\([^ ]+) ([^
]+)
\(.+))?" (VERSION NIL DEBUG-LEVEL DESTINATION NEXT-SERVER NIL PROTOCOL-VERSION LINK-UPTIME-IN-SECONDS BACKSTREAM-SENDQ UPSTREAM-SENDQ))
      (201 RPL-TRACECONNECTING "Try\\. ([^ ]+) ([^ ]+)" (CLASS SERVER))
      (202 RPL-TRACEHANDSHAKE "H\\.S\\. ([^ ]+) ([^ ]+)" (CLASS SERVER))
      (203 RPL-TRACEUNKNOWN "[^ ]* ([^ ]+)( (.+))?" (CLASS NIL CONNECTION-ADDRESS))
      (204 RPL-TRACEOPERATOR "Oper ([^ ]+) ([^ ]+)" (CLASS NICK))
      (205 RPL-TRACEUSER "User ([^ ]+) ([^ ]+)" (CLASS NICK))
      (206 RPL-TRACESERVER "Serv ([^ ]+) ([^S]+)S ([^C]+)C ([^
]+)
\([^@]+)@([^ ]+)( V(.+))?" (CLASS SERVERS CLIENTS SERVER USER HOST NIL PROTOCOL-VERSION))
      (207 RPL-TRACESERVICE "Service ([^ ]+) ([^ ]+) ([^ ]+) ([^ ]+)" (CLASS NAME TYPE ACTIVE-TYPE))
      (208 RPL-TRACENEWTYPE "([^ ]+) 0 ([^ ]+)" (NEWTYPE CLIENT-NAME))
      (209 RPL-TRACECLASS "Class ([^ ]+) ([^ ]+)" (CLASS COUNT))
      (210 RPL-TRACERECONNECT "" NIL)
      (211 RPL-STATSLINKINFO "([^ ]+) ([^ ]+) ([^ ]+) ([^ ]+) ([^ ]+) ([^ ]+) ([^ ]+)" (LINKNAME SENDQ SENT-MSGS SENT-BYTES RECVD-MSGS RCVD-BYTES TIME-OPEN))
      (212 RPL-STATSCOMMANDS "([^ ]+) ([^ ]+)( ([^ ]+) (.+))?" (COMMAND COUNT NIL BYTE-COUNT REMOTE-COUNT))
      (213 RPL-STATSCLINE "C ([^ ]+) \\* ([^ ]+) ([^ ]+) ([^ ]+)" (HOST NAME PORT CLASS))
      (214 RPL-STATSNLINE "N ([^ ]+) \\* ([^ ]+) ([^ ]+) ([^ ]+)" (HOST NAME PORT CLASS))
      (215 RPL-STATSILINE "I ([^ ]+) \\* ([^ ]+) ([^ ]+) ([^ ]+)" (HOST STATS-HOST PORT CLASS))
      (216 RPL-STATSKLINE "K ([^ ]+) \\* ([^ ]+) ([^ ]+) ([^ ]+)" (HOST USERNAME PORT CLASS))
      (217 RPL-STATSQLINE "" NIL)
      (218 RPL-STATSYLINE "Y ([^ ]+) ([^ ]+) ([^ ]+) ([^ ]+)" (CLASS PING-FREQ CONNECT-FREQ MAX-SENDQ))
      (219 RPL-ENDOFSTATS "([^ ]+) (:.*)" (QUERY INFO))
      (221 RPL-UMODEIS "([^ ]+)( (.+))?" (USER-MODES NIL USER-MODE-PARAMS))
      (228 RPL-STATSQLINE "" NIL)
      (231 RPL-SERVICEINFO "" NIL)
      (232 RPL-ENDOFSERVICES "" NIL)
      (233 RPL-SERVICE "" NIL)
      (234 RPL-SERVLIST "([^ ]+) ([^ ]+) ([^ ]+) ([^ ]+) ([^ ]+) ([^ ]+)" (NAME SERVER MASK TYPE HOPCOUNT INFO))
      (235 RPL-SERVLISTEND "([^ ]+) ([^ ]+) (:.*)" (MASK TYPE INFO))
      (236 RPL-STATSVERBOSE "" NIL)
      (237 RPL-STATSENGINE "" NIL)
      (238 RPL-STATSFLINE "" NIL)
      (239 RPL-STATSIAUTH "" NIL)
      (241 RPL-STATSLLINE "L ([^ ]+) \\* ([^ ]+) ([^ ]+)" (HOSTMASK SERVERNAME MAXDEPTH))
      (242 RPL-STATSUPTIME "(:.*)" (INFO))
      (243 RPL-STATSOLINE "O ([^ ]+) \\* ([^ ]+)( :(.*))?" (HOSTMASK NICK NIL INFO))
      (244 RPL-STATSHLINE "H ([^ ]+) \\* ([^ ]+)" (HOSTMASK SERVERNAME))
      (245 RPL-STATSSLINE "" NIL)
      (250 RPL-STATSDLINE "" NIL)
      (251 RPL-LUSERCLIENT "(:.*)" (INFO))
      (252 RPL-LUSEROP "([^ ]+) (:.*)" (INT INFO))
      (253 RPL-LUSERUNKNOWN "([^ ]+) (:.*)" (INT INFO))
      (254 RPL-LUSERCHANNELS "([^ ]+) (:.*)" (INT INFO))
      (255 RPL-LUSERME "(:.*)" (INFO))
      (256 RPL-ADMINME "([^ ]+) (:.*)" (SERVER INFO))
      (257 RPL-ADMINLOC1 "(:.*)" (INFO))
      (258 RPL-ADMINLOC2 "(:.*)" (INFO))
      (259 RPL-ADMINEMAIL "(:.*)" (INFO))
      (261 RPL-TRACELOG "File ([^ ]+) ([^ ]+)" (LOGFILE DEBUG-LEVEL))
      (262 RPL-TRACEEND "([^ ]+) ([^. ]+)(\\.([^ ]+))? (:.*)" (SERVER-NAME VERSION NIL DEBUG-LEVEL INFO))
      (263 RPL-TRYAGAIN "([^ ]+) (:.*)" (COMMAND INFO))
      (265 RPL-LOCALUSERS "" NIL)
      (266 RPL-GLOBALUSERS "" NIL)
      (267 RPL-START-NETSTAT "" NIL)
      (268 RPL-NETSTAT "" NIL)
      (269 RPL-END-NETSTAT "" NIL)
      (270 RPL-PRIVS "" NIL)
      (271 RPL-SILELIST "" NIL)
      (272 RPL-ENDOFSILELIST "" NIL)
      (273 RPL-NOTIFY "" NIL)
      (275 RPL-STATSDLINE "" NIL)
      (276 RPL-VCHANEXIST "" NIL)
      (277 RPL-VCHANLIST "" NIL)
      (278 RPL-VCHANHELP "" NIL)
      (280 RPL-GLIST "" NIL)
      (296 RPL-CHANINFO-KICKS "" NIL)
      (299 RPL-END-CHANINFO "" NIL)
      (300 RPL-NONE "" NIL)
      (301 RPL-AWAY "([^ ]+) (:.*)" (NICK INFO))
      (302 RPL-USERHOST "(:.*)" (INFO))
      (303 RPL-ISON "(:.*)" (INFO))
      (304 RPL-TEXT "" NIL)
      (305 RPL-UNAWAY "(:.*)" (INFO))
      (306 RPL-NOWAWAY "(:.*)" (INFO))
      (311 RPL-WHOISUSER "([^ ]+) ([^ ]+) ([^ ]+) \\* (:.*)" (NICK USER HOST INFO))
      (312 RPL-WHOISSERVER "([^ ]+) ([^ ]+) (:.*)" (NICK SERVER INFO))
      (313 RPL-WHOISOPERATOR "([^ ]+) (:.*)" (NICK INFO))
      (314 RPL-WHOWASUSER "([^ ]+) ([^ ]+) ([^ ]+) \\* (:.*)" (NICK USER HOST INFO))
      (315 RPL-ENDOFWHO "([^ ]+) (:.*)" (NAME INFO))
      (316 RPL-WHOISCHANOP "" NIL)
      (317 RPL-WHOISIDLE "([^ ]+) ([^ ]+) (:.*)" (NICK SECONDS INFO))
      (318 RPL-ENDOFWHOIS "([^ ]+) (:.*)" (NICK INFO))
      (319 RPL-WHOISCHANNELS "([^ ]+) (:.*)" (NICK INFO))
      (321 RPL-LISTSTART "Channels (:.*)" (INFO))
      (322 RPL-LIST "([^ ]+) ([^ ]+) (:.*)" (CHANNEL VISIBLE-COUNT INFO))
      (323 RPL-LISTEND "(:.*)" (INFO))
      (324 RPL-CHANNELMODEIS "([^ ]+) ([^ ]+) ([^ ]+)" (CHANNEL MODE MODE-PARAMS))
      (325 RPL-UNIQOPIS "([^ ]+) ([^ ]+)" (CHANNEL NICKNAME))
      (326 RPL-NOCHANPASS "" NIL)
      (327 RPL-CHPASSUNKNOWN "" NIL)
      (328 RPL-CHANNEL-URL "" NIL)
      (329 RPL-CREATIONTIME "" NIL)
      (331 RPL-NOTOPIC "([^ ]+) (:.*)" (CHANNEL INFO))
      (332 RPL-TOPIC "([^ ]+) (:.*)" (CHANNEL INFO))
      (333 RPL-TOPICWHOTIME "" NIL)
      (335 RPL-WHOISBOT "" NIL)
      (339 RPL-BADCHANPASS "" NIL)
      (340 RPL-USERIP "" NIL)
      (341 RPL-INVITING "([^ ]+) ([^ ]+)" (NICK CHANNEL))
      (342 RPL-SUMMONING "([^ ]+) (:.*)" (USER INFO))
      (345 RPL-INVITED "([^ ]+) ([^ ]+) ([^ ]+) (:.*)" (CHANNEL USER-BEING-INVITED USER-ISSUING-INVITE INFO))
      (346 RPL-INVITELIST "([^ ]+) ([^ ]+)" (CHANNEL INVITEMASK))
      (347 RPL-ENDOFINVITELIST "([^ ]+) (:.*)" (CHANNEL INFO))
      (348 RPL-EXCEPTLIST "([^ ]+) ([^ ]+)" (CHANNEL EXCEPTIONMASK))
      (349 RPL-ENDOFEXCEPTLIST "([^ ]+) (:.*)" (CHANNEL INFO))
      (351 RPL-VERSION "([^. ]+)(\\.([^ ]+))? ([^ ]+) (:.*)" (VERSION NIL DEBUGLEVEL SERVER INFO))
      (352 RPL-WHOREPLY "([^ ]+) ([^ ]+) ([^ ]+) ([^ ]+) ([^ ]+) ([^*@+ ]+\\*?[@+]?) (:.*)" (CHANNEL USER HOST SERVER NICK HG INFO))
      (353 RPL-NAMREPLY "[=*@]([^ ]+) (:.*)" (CHANNEL INFO))
      (354 RPL-WHOSPCRPL "" NIL)
      (355 RPL-NAMREPLY- "[=*@]([^ ]+) (:.*)" (CHANNEL INFO))
      (357 RPL-MAP "" NIL)
      (358 RPL-MAPMORE "" NIL)
      (359 RPL-MAPEND "" NIL)
      (361 RPL-KILLDONE "" NIL)
      (362 RPL-CLOSING "" NIL)
      (363 RPL-CLOSEEND "" NIL)
      (364 RPL-LINKS "([^ ]+) ([^ ]+) (:.*)" (MASK SERVER INFO))
      (365 RPL-ENDOFLINKS "([^ ]+) (:.*)" (MASK INFO))
      (366 RPL-ENDOFNAMES "([^ ]+) (:.*)" (CHANNEL INFO))
      (367 RPL-BANLIST "([^ ]+) ([^ ]+)( ([^ ]+) (:.*))?" (CHANNEL BANID TIME-LEFT INFO))
      (368 RPL-ENDOFBANLIST "([^ ]+) (:.*)" (CHANNEL INFO))
      (369 RPL-ENDOFWHOWAS "([^ ]+) (:.*)" (NICK INFO))
      (371 RPL-INFO "(:.*)" (INFO))
      (372 RPL-MOTD "(:.*)" (INFO))
      (373 RPL-INFOSTART "" NIL)
      (374 RPL-ENDOFINFO "(:.*)" (INFO))
      (375 RPL-MOTDSTART "(:.*)" (INFO))
      (376 RPL-ENDOFMOTD "(:.*)" (INFO))
      (381 RPL-YOUREOPER "(:.*)" (INFO))
      (382 RPL-REHASHING "([^ ]+) (:.*)" (CONFIG-FILE INFO))
      (383 RPL-YOURESERVICE "(:.*)" (INFO))
      (384 RPL-MYPORTIS "" NIL)
      (385 RPL-NOTOPERANYMORE "" NIL)
      (388 RPL-ALIST "" NIL)
      (389 RPL-ENDOFALIST "" NIL)
      (391 RPL-TIME "([^ ]+) (:.*)" (SERVER INFO))
      (392 RPL-USERSSTART "(:.*)" (INFO))
      (393 RPL-USERS "(:.*)" (INFO))
      (394 RPL-ENDOFUSERS "(:.*)" (INFO))
      (395 RPL-NOUSERS "(:.*)" (INFO))
      (396 RPL-HOSTHIDDEN "" NIL)
      (400 ERR-UNKNOWNERROR "([^ ]+)( ?)? (:.*)" (COMMAND ? INFO))
      (401 ERR-NOSUCHNICK "([^ ]+) (:.*)" (NICK INFO))
      (402 ERR-NOSUCHSERVER "([^ ]+) (:.*)" (SERVER INFO))
      (403 ERR-NOSUCHCHANNEL "([^ ]+) (:.*)" (CHANNEL INFO))
      (404 ERR-CANNOTSENDTOCHAN "([^ ]+) (:.*)" (CHANNEL INFO))
      (405 ERR-TOOMANYCHANNELS "([^ ]+) (:.*)" (CHANNEL INFO))
      (406 ERR-WASNOSUCHNICK "([^ ]+) (:.*)" (NICK INFO))
      (407 ERR-TOOMANYTARGETS "([^ ]+) (:.*)" (TARGET INFO))
      (408 ERR-NOSUCHSERVICE "([^ ]+) (:.*)" (SERVICE-NAME INFO))
      (409 ERR-NOORIGIN "(:.*)" (INFO))
      (411 ERR-NORECIPIENT "(:.*)" (INFO))
      (412 ERR-NOTEXTTOSEND "(:.*)" (INFO))
      (413 ERR-NOTOPLEVEL "([^ ]+) (:.*)" (MASK INFO))
      (414 ERR-WILDTOPLEVEL "([^ ]+) (:.*)" (MASK INFO))
      (415 ERR-BADMASK "([^ ]+) (:.*)" (MASK INFO))
      (419 ERR-LENGTHTRUNCATED "" NIL)
      (421 ERR-UNKNOWNCOMMAND "([^ ]+) (:.*)" (COMMAND INFO))
      (422 ERR-NOMOTD "(:.*)" (INFO))
      (423 ERR-NOADMININFO "([^ ]+) (:.*)" (SERVER INFO))
      (424 ERR-FILEERROR "(:.*)" (INFO))
      (425 ERR-NOOPERMOTD "" NIL)
      (429 ERR-TOOMANYAWAY "" NIL)
      (430 ERR-EVENTNICKCHANGE "" NIL)
      (431 ERR-NONICKNAMEGIVEN "(:.*)" (INFO))
      (432 ERR-ERRONEUSNICKNAME "([^ ]+) (:.*)" (NICK INFO))
      (433 ERR-NICKNAMEINUSE "([^ ]+) (:.*)" (NICK INFO))
      (436 ERR-NICKCOLLISION "([^ ]+) (:.*)" (NICK INFO))
      (437 ERR-UNAVAILRESOURCE "([^ ]+) (:.*)" (RESOURCE INFO))
      (439 ERR-TARGETTOOFAST "" NIL)
      (440 ERR-SERVICESDOWN "" NIL)
      (441 ERR-USERNOTINCHANNEL "([^ ]+) ([^ ]+) (:.*)" (NICK CHANNEL INFO))
      (442 ERR-NOTONCHANNEL "([^ ]+) (:.*)" (CHANNEL INFO))
      (443 ERR-USERONCHANNEL "([^ ]+) ([^ ]+)( :(.*))?" (NICK CHANNEL NIL INFO))
      (444 ERR-NOLOGIN "([^ ]+) (:.*)" (USER INFO))
      (445 ERR-SUMMONDISABLED "(:.*)" (INFO))
      (446 ERR-USERSDISABLED "(:.*)" (INFO))
      (447 ERR-NONICKCHANGE "" NIL)
      (449 ERR-NOTIMPLEMENTED "Unspecified" NIL)
      (451 ERR-NOTREGISTERED "(:.*)" (INFO))
      (452 ERR-IDCOLLISION "" NIL)
      (453 ERR-NICKLOST "" NIL)
      (455 ERR-HOSTILENAME "" NIL)
      (456 ERR-ACCEPTFULL "" NIL)
      (457 ERR-ACCEPTEXIST "" NIL)
      (458 ERR-ACCEPTNOT "" NIL)
      (459 ERR-NOHIDING "" NIL)
      (460 ERR-NOTFORHALFOPS "" NIL)
      (461 ERR-NEEDMOREPARAMS "([^ ]+) (:.*)" (COMMAND INFO))
      (462 ERR-ALREADYREGISTERED "(:.*)" (INFO))
      (463 ERR-NOPERMFORHOST "(:.*)" (INFO))
      (464 ERR-PASSWDMISMATCH "(:.*)" (INFO))
      (465 ERR-YOUREBANNEDCREEP "(:.*)" (INFO))
      (466 ERR-YOUWILLBEBANNED "" NIL)
      (467 ERR-KEYSET "([^ ]+) (:.*)" (CHANNEL INFO))
      (469 ERR-LINKSET "" NIL)
      (471 ERR-CHANNELISFULL "([^ ]+) (:.*)" (CHANNEL INFO))
      (472 ERR-UNKNOWNMODE "([^ ]+) (:.*)" (CHAR INFO))
      (473 ERR-INVITEONLYCHAN "([^ ]+) (:.*)" (CHANNEL INFO))
      (474 ERR-BANNEDFROMCHAN "([^ ]+) (:.*)" (CHANNEL INFO))
      (475 ERR-BADCHANNELKEY "([^ ]+) (:.*)" (CHANNEL INFO))
      (476 ERR-BADCHANMASK "([^ ]+) (:.*)" (CHANNEL INFO))
      (477 ERR-NOCHANMODES "([^ ]+) (:.*)" (CHANNEL INFO))
      (478 ERR-BANLISTFULL "([^ ]+) ([^ ]+) (:.*)" (CHANNEL CHAR INFO))
      (481 ERR-NOPRIVILEGES "(:.*)" (INFO))
      (482 ERR-CHANOPRIVSNEEDED "([^ ]+) (:.*)" (CHANNEL INFO))
      (483 ERR-CANTKILLSERVER "(:.*)" (INFO))
      (484 ERR-RESTRICTED "(:.*)" (INFO))
      (485 ERR-UNIQOPRIVSNEEDED "(:.*)" (INFO))
      (488 ERR-TSLESSCHAN "" NIL)
      (491 ERR-NOOPERHOST "(:.*)" (INFO))
      (492 ERR-NOSERVICEHOST "" NIL)
      (493 ERR-NOFEATURE "" NIL)
      (494 ERR-BADFEATURE "" NIL)
      (495 ERR-BADLOGTYPE "" NIL)
      (496 ERR-BADLOGSYS "" NIL)
      (497 ERR-BADLOGVALUE "" NIL)
      (498 ERR-ISOPERLCHAN "" NIL)
      (499 ERR-CHANOWNPRIVNEEDED "" NIL)
      (501 ERR-UMODEUNKNOWNFLAG "(:.*)" (INFO))
      (502 ERR-USERSDONTMATCH "(:.*)" (INFO))
      (504 ERR-USERNOTONSERV "" NIL)
      (511 ERR-SILELISTFULL "" NIL)
      (512 ERR-TOOMANYWATCH "" NIL)
      (513 ERR-BADPING "" NIL)
      (515 ERR-BADEXPIRE "" NIL)
      (516 ERR-DONTCHEAT "" NIL)
      (517 ERR-DISABLED "([^ ]+) (:.*)" (COMMAND INFO))
      (521 ERR-LISTSYNTAX "" NIL)
      (522 ERR-WHOSYNTAX "" NIL)
      (523 ERR-WHOLIMEXCEED "" NIL)
      (525 ERR-REMOTEPFX "([^ ]+) (:.*)" (NICKNAME INFO))
      (526 ERR-PFXUNROUTABLE "([^ ]+) (:.*)" (NICKNAME INFO))
      (550 ERR-BADHOSTMASK "" NIL)
      (551 ERR-HOSTUNAVAIL "" NIL)
      (552 ERR-USINGSLINE "" NIL)
      (553 ERR-STATSSLINE "" NIL)
      (600 RPL-LOGON "" NIL)
      (601 RPL-LOGOFF "" NIL)
      (602 RPL-WATCHOFF "" NIL)
      (603 RPL-WATCHSTAT "" NIL)
      (604 RPL-NOWON "" NIL)
      (605 RPL-NOWOFF "" NIL)
      (606 RPL-WATCHLIST "" NIL)
      (607 RPL-ENDOFWATCHLIST "" NIL)
      (608 RPL-WATCHCLEAR "" NIL)
      (611 RPL-ISLOCOP "" NIL)
      (612 RPL-ISNOTOPER "" NIL)
      (613 RPL-ENDOFISOPER "" NIL)
      (616 RPL-WHOISHOST "" NIL)
      (618 RPL-DCCLIST "" NIL)
      (621 RPL-RULES "" NIL)
      (622 RPL-ENDOFRULES "" NIL)
      (623 RPL-MAPMORE "" NIL)
      (624 RPL-OMOTDSTART "" NIL)
      (625 RPL-OMOTD "" NIL)
      (626 RPL-ENDOFO "" NIL)
      (630 RPL-SETTINGS "" NIL)
      (631 RPL-ENDOFSETTINGS "" NIL)
      (640 RPL-DUMPING "" NIL)
      (641 RPL-DUMPRPL "" NIL)
      (642 RPL-EODUMP "" NIL)
      (660 RPL-TRACEROUTE-HOP "([^ ]+) ([^ ]+) (([^ ]+)( ([^ ]+|\\*))? (.+))?" (TARGET HOP-COUNT NIL ADDRESS NIL HOSTNAME USEC-PING))
      (661 RPL-TRACEROUTE-START "([^ ]+) ([^ ]+) ([^ ]+) ([^ ]+)" (TARGET TARGET-FQDN TARGET-ADDRESS MAX-HOPS))
      (662 RPL-MODECHANGEWARN "([+-]?[^ ]+) (:.*)" (MODE-CHAR INFO))
      (663 RPL-CHANREDIR "([^ ]+) ([^ ]+) (:.*)" (OLD-CHAN NEW-CHAN INFO))
      (664 RPL-SERVMODEIS "([^ ]+) ([^ ]+) ([^.]+).." (SERVER MODES PARAMETERS))
      (665 RPL-OTHERUMODEIS "([^ ]+) ([^ ]+)" (NICKNAME MODES))
      (666 RPL-ENDOF-GENERIC "([^ ]+) (([^ ]+))* (:.*)" (COMMAND PARAMETER INFO))
      (670 RPL-WHOWASDETAILS "([^ ]+) ([^ ]+) (:.*)" (NICK TYPE INFO))
      (671 RPL-WHOISSECURE "([^ ]+) ([^ ]+)( :(.*))?" (NICK TYPE NIL INFO))
      (672 RPL-UNKNOWNMODES "([^ ]+) (:.*)" (MODES INFO))
      (673 RPL-CANNOTSETMODES "([^ ]+) (:.*)" (MODES INFO))
      (678 RPL-LUSERSTAFF "([^ ]+) (:.*)" (STAFF-ONLINE-COUNT INFO))
      (679 RPL-TIMEONSERVERIS "([^ ]+)( ([^ ]+|0))? ([^ ]+) ([^ ]+) (:.*)" (SECONDS NIL NANOSECONDS TIMEZONE FLAGS INFO))
      (682 RPL-NETWORKS "([^ ]+) ([^ ]+) ([^ ]+) (:.*)" (NAME THROUGH-NAME HOPS INFO))
      (687 RPL-YOURLANGUAGEIS "([^ ]+) (:.*)" (CODES INFO))
      (688 RPL-LANGUAGE "([^ ]+) ([^ ]+) ([^ ]+) ([^ ]+) * (:.*)" (CODE REVISION MAINTAINER FLAGS INFO))
      (689 RPL-WHOISSTAFF "(:.*)" (INFO))
      (690 RPL-WHOISLANGUAGE "([^ ]+) ([^ ]+)" (NICK LANGUAGE-CODES))
      (702 RPL-MODLIST "" NIL)
      (703 RPL-ENDOFMODLIST "(:.*)" (INFO))
      (704 RPL-HELPSTART "([^ ]+) (:.*)" (COMMAND INFO))
      (705 RPL-HELPTXT "([^ ]+) (:.*)" (COMMAND INFO))
      (706 RPL-ENDOFHELP "([^ ]+) (:.*)" (COMMAND INFO))
      (708 RPL-ETRACEFULL "" NIL)
      (709 RPL-ETRACE "" NIL)
      (710 RPL-KNOCK "([^ ]+) ([^!]+)!([^@]+)@([^ ]+) (:.*)" (CHANNEL NICK USER HOST INFO))
      (711 RPL-KNOCKDLVR "([^ ]+) (:.*)" (CHANNEL INFO))
      (712 ERR-TOOMANYKNOCK "([^ ]+) (:.*)" (CHANNEL INFO))
      (713 ERR-CHANOPEN "([^ ]+) (:.*)" (CHANNEL INFO))
      (714 ERR-KNOCKONCHAN "([^ ]+) (:.*)" (CHANNEL INFO))
      (715 ERR-KNOCKDISABLED "(:.*)" (INFO))
      (716 RPL-TARGUMODEG "([^ ]+) (:.*)" (NICK INFO))
      (717 RPL-TARGNOTIFY "([^ ]+) (:.*)" (NICK INFO))
      (718 RPL-UMODEGMSG "([^ ]+) ([^@]+)@([^ ]+) (:.*)" (NICK USER HOST INFO))
      (720 RPL-OMOTDSTART "(:.*)" (INFO))
      (721 RPL-OMOTD "(:.*)" (INFO))
      (722 RPL-ENDOFOMOTD "(:.*)" (INFO))
      (723 ERR-NOPRIVS "([^ ]+) (:.*)" (COMMAND INFO))
      (724 RPL-TESTMARK "([^!]+)!([^@]+)@([^ ]+) ([^ ]+) ([^ ]+) (:.*)" (NICK USER HOST A B INFO))
      (725 RPL-TESTLINE "" NIL)
      (726 RPL-NOTESTLINE "([^ ]+) (:.*)" (INT INFO))
      (771 RPL-XINFO "" NIL)
      (773 RPL-XINFOSTART "" NIL)
      (774 RPL-XINFOEND "" NIL)
      (972 ERR-CANNOTDOCOMMAND "" NIL)
      (973 ERR-CANNOTCHANGEUMODE "([^ ]+) (:.*)" (MODE-CHAR INFO))
      (974 ERR-CANNOTCHANGECHANMODE "([^ ]+) (:.*)" (MODE-CHAR INFO))
      (975 ERR-CANNOTCHANGESERVERMODE "([^ ]+) (:.*)" (MODE-CHAR INFO))
      (976 ERR-CANNOTSENDTONICK "([^ ]+) (:.*)" (NICK INFO))
      (977 ERR-UNKNOWNSERVERMODE "([^ ]+) (:.*)" (MODECHAR INFO))
      (979 ERR-SERVERMODELOCK "([^ ]+) (:.*)" (TARGET INFO))
      (980 ERR-BADCHARENCODING "([^ ]+) ([^ ]+) (:.*)" (COMMAND CHARSET INFO))
      (981 ERR-TOOMANYLANGUAGES "([^ ]+) (:.*)" (MAX-LANGS INFO))
      (982 ERR-NOLANGUAGE "([^ ]+) (:.*)" (LANGUAGE-CODE INFO))
      (983 ERR-TEXTTOOSHORT "([^ ]+) (:.*)" (COMMAND INFO))
      (999 ERR-NUMERIC-ERR "" NIL))))
(macrolet ((define-all-irc-replies ()
             `(progn
                ,@(loop for (code name regex args) in *reply-descriptors*
                        collect `(define-irc-reply ,name ,code (,regex ,@args))))))
  (define-all-irc-replies))
