#|
 This file is a part of Maiden
 (c) 2016 Shirakumo http://tymoon.eu (shinmera@tymoon.eu)
 Author: Nicolas Hafner <shinmera@tymoon.eu>
|#

(in-package #:org.shirakumo.maiden.agents.talk)

(defvar *language-code-map*
  '(("Afrikaans" . "af")
    ("Albanian" . "sq")
    ("Amharic" . "am")
    ("Arabic" . "ar")
    ("Armenian" . "hy")
    ("Azeerbaijani" . "az")
    ("Basque" . "eu")
    ("Belarusian" . "be")
    ("Bengali" . "bn")
    ("Bosnian" . "bs")
    ("Bulgarian" . "bg")
    ("Catalan" . "ca")
    ("Cebuano" . "ceb")
    ("Chichewa" . "ny")
    ("Chinese" . "zh")
    ("Simplified Chinese" . "zh-CN")
    ("Traditional Chinese" . "zh-TW")
    ("Corsican" . "co")
    ("Croatian" . "hr")
    ("Czech" . "cs")
    ("Danish" . "da")
    ("Dutch" . "nl")
    ("English" . "en")
    ("Esperanto" . "eo")
    ("Estonian" . "et")
    ("Filipino" . "tl")
    ("Finnish" . "fi")
    ("French" . "fr")
    ("Frisian" . "fy")
    ("Galician" . "gl")
    ("Georgian" . "ka")
    ("German" . "de")
    ("Greek" . "el")
    ("Gujarati" . "gu")
    ("Haitian Creole" . "ht")
    ("Hausa" . "ha")
    ("Hawaiian" . "haw")
    ("Hebrew" . "iw")
    ("Hindi" . "hi")
    ("Hmong" . "hmn")
    ("Hungarian" . "hu")
    ("Icelandic" . "is")
    ("Igbo" . "ig")
    ("Indonesian" . "id")
    ("Irish" . "ga")
    ("Italian" . "it")
    ("Japanese" . "ja")
    ("Javanese" . "jw")
    ("Kannada" . "kn")
    ("Kazakh" . "kk")
    ("Khmer" . "km")
    ("Korean" . "ko")
    ("Kurdish" . "ku")
    ("Kyrgyz" . "ky")
    ("Lao" . "lo")
    ("Latin" . "la")
    ("Latvian" . "lv")
    ("Lithuanian" . "lt")
    ("Luxembourgish" . "lb")
    ("Macedonian" . "mk")
    ("Malagasy" . "mg")
    ("Malay" . "ms")
    ("Malayalam" . "ml")
    ("Maltese" . "mt")
    ("Maori" . "mi")
    ("Marathi" . "mr")
    ("Mongolian" . "mn")
    ("Burmese" . "my")
    ("Nepali" . "ne")
    ("Norwegian" . "no")
    ("Pashto" . "ps")
    ("Persian" . "fa")
    ("Polish" . "pl")
    ("Portuguese" . "pt")
    ("Punjabi" . "ma")
    ("Romanian" . "ro")
    ("Russian" . "ru")
    ("Samoan" . "sm")
    ("Scots Gaelic" . "gd")
    ("Serbian" . "sr")
    ("Sesotho" . "st")
    ("Shona" . "sn")
    ("Sindhi" . "sd")
    ("Sinhala" . "si")
    ("Slovak" . "sk")
    ("Slovenian" . "sl")
    ("Somali" . "so")
    ("Spanish" . "es")
    ("Sundanese" . "su")
    ("Swahili" . "sw")
    ("Swedish" . "sv")
    ("Tajik" . "tg")
    ("Tamil" . "ta")
    ("Telugu" . "te")
    ("Thai" . "th")
    ("Turkish" . "tr")
    ("Ukrainian" . "uk")
    ("Urdu" . "ur")
    ("Uzbek" . "uz")
    ("Vietnamese" . "vi")
    ("Welsh" . "cy")
    ("Xhosa" . "xh")
    ("Yiddish" . "yi")
    ("Yoruba" . "yo")
    ("Zulu" . "zu")))

(defun language-code (language)
  (or (loop for (name . code) in *language-code-map*
            do (when (or (search language name :test #'char-equal)
                         (search name language :test #'char-equal))
                 (return code)))
      language))
