#|
 This file is a part of Maiden
 (c) 2017 Shirakumo http://tymoon.eu (shinmera@tymoon.eu)
 Author: Nicolas Hafner <shinmera@tymoon.eu>
|#

(in-package #:org.shirakumo.maiden.agents.lookup)

(define-webpage-lookup clhs (term)
  (format NIL "http://l1sp.org/cl/~a" (drakma:url-encode term :utf-8)))

(macrolet ((define-l1sp-lookups (&rest lookups)
             `(progn ,@(loop for lookup in lookups
                             collect `(define-webpage-lookup ,lookup (term)
                                        (format NIL "http://l1sp.org/~a/~a"
                                                ,(string-downcase lookup) (drakma:url-encode term :utf-8)))))))
  (define-l1sp-lookups asdf ccl cffi clim clisp clx mop pcl sbcl))

(define-table-lookup lichat
  (("1" "wire format") "https://github.com/Shirakumo/lichat-protocol#1-wire-format")
  (("1.1" "symbols") "https://github.com/Shirakumo/lichat-protocol#11-symbols")
  (("1.2" "objects") "https://github.com/Shirakumo/lichat-protocol#12-objects")
  (("1.3" "null characters") "https://github.com/Shirakumo/lichat-protocol#13-null-characters")
  (("2" "server objects") "https://github.com/Shirakumo/lichat-protocol#2-server-objects")
  (("2.1" "connection") "https://github.com/Shirakumo/lichat-protocol#21-connection")
  (("2.2" "user") "https://github.com/Shirakumo/lichat-protocol#22-user")
  (("2.2.1" "user name constraints") "https://github.com/Shirakumo/lichat-protocol#221-user-name-constraints")
  (("2.3" "profile") "https://github.com/Shirakumo/lichat-protocol#23-profile")
  (("2.4" "channel") "https://github.com/Shirakumo/lichat-protocol#24-channel")
  (("2.4.1" "primary channels") "https://github.com/Shirakumo/lichat-protocol#241-primary-channels")
  (("2.4.2" "anonymous channels") "https://github.com/Shirakumo/lichat-protocol#242-anonymous-channels")
  (("2.4.3" "regular channels") "https://github.com/Shirakumo/lichat-protocol#243-regular-channels")
  (("2.4.4" "channel name constraints") "https://github.com/Shirakumo/lichat-protocol#244-channel-name-constraints")
  (("2.5" "permission rules") "https://github.com/Shirakumo/lichat-protocol#25-permission-rules")
  (("3" "general interaction") "https://github.com/Shirakumo/lichat-protocol#3-general-interaction")
  (("3.1" "null termination of updates") "https://github.com/Shirakumo/lichat-protocol#31-null-termination-of-updates")
  (("4" "connection") "https://github.com/Shirakumo/lichat-protocol#4-connection")
  (("4.1" "connection establishment") "https://github.com/Shirakumo/lichat-protocol#41-connection-establishment")
  (("4.2" "connection maintenance") "https://github.com/Shirakumo/lichat-protocol#42-connection-maintenance")
  (("4.3" "connection closure") "https://github.com/Shirakumo/lichat-protocol#43-connection-closure")
  (("5" "client interaction") "https://github.com/Shirakumo/lichat-protocol#5-client-interaction")
  (("5.1" "general update checks") "https://github.com/Shirakumo/lichat-protocol#51-general-update-checks")
  (("5.2" "profile registration") "https://github.com/Shirakumo/lichat-protocol#52-profile-registration")
  (("5.3" "channel creation & management") "https://github.com/Shirakumo/lichat-protocol#53-channel-creation--management")
  (("5.4" "channel interaction") "https://github.com/Shirakumo/lichat-protocol#54-channel-interaction")
  (("5.4.1" "joining a channel") "https://github.com/Shirakumo/lichat-protocol#541-joining-a-channel")
  (("5.4.2" "leaving a channel") "https://github.com/Shirakumo/lichat-protocol#542-leaving-a-channel")
  (("5.4.3" "pulling a user") "https://github.com/Shirakumo/lichat-protocol#543-pulling-a-user")
  (("5.4.4" "kicking a user") "https://github.com/Shirakumo/lichat-protocol#544-kicking-a-user")
  (("5.4.5" "sending a message") "https://github.com/Shirakumo/lichat-protocol#545-sending-a-message")
  (("5.5" "server information retrieval") "https://github.com/Shirakumo/lichat-protocol#55-server-information-retrieval")
  (("5.5.1" "listing public channels") "https://github.com/Shirakumo/lichat-protocol#551-listing-public-channels")
  (("5.5.2" "listing all users of a channel") "https://github.com/Shirakumo/lichat-protocol#552-listing-all-users-of-a-channel")
  (("5.5.3" "requesting information about a user") "https://github.com/Shirakumo/lichat-protocol#553-requesting-information-about-a-user")
  (("6" "protocol extension") "https://github.com/Shirakumo/lichat-protocol#6-protocol-extension")
  ("*DEFAULT-ANONYMOUS-CHANNEL-PERMISSIONS*" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:*DEFAULT-ANONYMOUS-CHANNEL-PERMISSIONS*")
  ("*DEFAULT-CHANNEL-LIFETIME*" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:*DEFAULT-CHANNEL-LIFETIME*")
  ("*DEFAULT-PRIMARY-CHANNEL-PERMISSIONS*" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:*DEFAULT-PRIMARY-CHANNEL-PERMISSIONS*")
  ("*DEFAULT-PROFILE-LIFETIME*" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:*DEFAULT-PROFILE-LIFETIME*")
  ("*DEFAULT-REGULAR-CHANNEL-PERMISSIONS*" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:*DEFAULT-REGULAR-CHANNEL-PERMISSIONS*")
  ("*ID-COUNTER*" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:*ID-COUNTER*")
  ("ALREADY-IN-CHANNEL" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:ALREADY-IN-CHANNEL")
  ("BAD-NAME" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:BAD-NAME")
  ("CHANNEL" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:CHANNEL")
  ("CHANNEL-UPDATE" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:CHANNEL-UPDATE")
  ("CHANNELNAME-TAKEN" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:CHANNELNAME-TAKEN")
  ("CHANNELS" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:CHANNELS")
  ("CONNECT" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:CONNECT")
  ("CONNECTION" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:CONNECTION")
  ("CONNECTION-UNSTABLE" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:CONNECTION-UNSTABLE")
  ("CREATE" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:CREATE")
  ("DISCONNECT" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:DISCONNECT")
  ("FAILURE" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:FAILURE")
  ("INCOMPATIBLE-VERSION" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:INCOMPATIBLE-VERSION")
  ("INSUFFICIENT-PERMISSIONS" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:INSUFFICIENT-PERMISSIONS")
  ("INVALID-PASSWORD" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:INVALID-PASSWORD")
  ("INVALID-PERMISSIONS" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:INVALID-PERMISSIONS")
  ("INVALID-UPDATE" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:INVALID-UPDATE")
  ("JOIN" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:JOIN")
  ("KICK" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:KICK")
  ("LEAVE" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:LEAVE")
  ("MALFORMED-UPDATE" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:MALFORMED-UPDATE")
  ("MESSAGE" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:MESSAGE")
  ("NAMED-OBJECT" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:NAMED-OBJECT")
  ("NO-SUCH-CHANNEL" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:NO-SUCH-CHANNEL")
  ("NO-SUCH-PROFILE" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:NO-SUCH-PROFILE")
  ("NO-SUCH-USER" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:NO-SUCH-USER")
  ("NOT-IN-CHANNEL" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:NOT-IN-CHANNEL")
  ("PERMISSIONS" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:PERMISSIONS")
  ("PING" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:PING")
  ("PONG" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:PONG")
  ("PROFILE" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:PROFILE")
  ("PULL" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:PULL")
  ("REGISTER" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:REGISTER")
  ("SERVER-OBJECT" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:SERVER-OBJECT")
  ("TARGET-UPDATE" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:TARGET-UPDATE")
  ("TEXT-UPDATE" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:TEXT-UPDATE")
  ("TOO-MANY-CONNECTIONS" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:TOO-MANY-CONNECTIONS")
  ("TOO-MANY-UPDATES" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:TOO-MANY-UPDATES")
  ("UPDATE" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:UPDATE")
  ("UPDATE-FAILURE" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:UPDATE-FAILURE")
  ("USER" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:USER")
  ("USER-INFO" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:USER-INFO")
  ("USERNAME-MISMATCH" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:USERNAME-MISMATCH")
  ("USERNAME-TAKEN" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:USERNAME-TAKEN")
  ("USERS" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:USERS")
  ("WIRE-OBJECT" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:WIRE-OBJECT")
  ("INCOMPATIBLE-VALUE-TYPE-FOR-SLOT" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:INCOMPATIBLE-VALUE-TYPE-FOR-SLOT")
  ("INCOMPLETE-TOKEN" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:INCOMPLETE-TOKEN")
  ("MISSING-CLOCK" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:MISSING-CLOCK")
  ("MISSING-ID" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:MISSING-ID")
  ("MISSING-UPDATE-ARGUMENT" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:MISSING-UPDATE-ARGUMENT")
  ("PRINTER-CONDITION" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:PRINTER-CONDITION")
  ("PROTOCOL-CONDITION" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:PROTOCOL-CONDITION")
  ("READER-CONDITION" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:READER-CONDITION")
  ("UNKNOWN-SYMBOL" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:UNKNOWN-SYMBOL")
  ("UNKNOWN-WIRE-OBJECT" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:UNKNOWN-WIRE-OBJECT")
  ("UNPRINTABLE-OBJECT" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:UNPRINTABLE-OBJECT")
  ("WIRE-CONDITION" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:WIRE-CONDITION")
  ("CHANNEL" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:CHANNEL")
  ("CHANNELS" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:CHANNELS")
  ("CLOCK" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:CLOCK")
  ("CONNECTIONS" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:CONNECTIONS")
  ("FROM" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:FROM")
  ("ID" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:ID")
  ("LIFETIME" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:LIFETIME")
  ("NAME" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:NAME")
  ("PASSWORD" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:PASSWORD")
  ("PERMISSIONS" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:PERMISSIONS")
  ("REGISTERED" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:REGISTERED")
  ("TARGET" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:TARGET")
  ("TEXT" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:TEXT")
  ("UPDATE-ID" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:UPDATE-ID")
  ("USER" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:USER")
  ("USERS" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:USERS")
  ("VERSION" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:VERSION")
  ("CHANNELNAME-P" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:CHANNELNAME-P")
  ("FROM-WIRE" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:FROM-WIRE")
  ("ID-P" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:ID-P")
  ("NEXT-ID" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:NEXT-ID")
  ("PASSWORD-P" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:PASSWORD-P")
  ("PROTOCOL-VERSION" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:PROTOCOL-VERSION")
  ("TO-WIRE" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:TO-WIRE")
  ("USERNAME-P" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:USERNAME-P")
  ("WHITESPACE-P" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:WHITESPACE-P")
  ("OBJECT" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:OBJECT")
  ("SYMBOL-DESIGNATOR" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:SYMBOL-DESIGNATOR")
  ("UPDATE" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:UPDATE")
  ("DEFINE-PROTOCOL-CLASS" "https://shirakumo.github.io/lichat-protocol/#LICHAT-PROTOCOL:DEFINE-PROTOCOL-CLASS"))

(define-table-lookup radiance
  (("1" "radiance concepts & parts") "https://github.com/shirakumo/radiance#1-radiance-concepts--parts")
  (("1.1" "uri") "https://github.com/shirakumo/radiance#11-uri")
  (("1.2" "request and response") "https://github.com/shirakumo/radiance#12-request-and-response")
  (("1.3" "route") "https://github.com/shirakumo/radiance#13-route")
  (("1.4" "uri dispatcher") "https://github.com/shirakumo/radiance#1.4-uri-dispatcher")
  (("1.5" "page") "https://github.com/shirakumo/radiance#15-page")
  (("1.6" "api endpoint") "https://github.com/shirakumo/radiance#16-api-endpoint")
  (("1.7" "options") "https://github.com/shirakumo/radiance#17-options")
  (("1.8" "module") "https://github.com/shirakumo/radiance#18-module")
  (("1.9" "hooks") "https://github.com/shirakumo/radiance#19-hooks")
  (("1.10" "interface") "https://github.com/shirakumo/radiance#110-interface")
  (("1.11" "environment") "https://github.com/shirakumo/radiance#111-environment")
  (("1.12" "instance management") "https://github.com/shirakumo/radiance#112-instance-management")
  (("2" "standard interfaces") "https://github.com/shirakumo/radiance#2-standard-interfaces")
  (("2.1" "admin") "https://github.com/shirakumo/radiance#21-admin")
  (("2.2" "auth") "https://github.com/shirakumo/radiance#22-auth")
  (("2.3" "ban") "https://github.com/shirakumo/radiance#23-ban")
  (("2.4" "cache") "https://github.com/shirakumo/radiance#24-cache")
  (("2.5" "database") "https://github.com/shirakumo/radiance#25-database")
  (("2.6" "logger") "https://github.com/shirakumo/radiance#26-logger")
  (("2.7" "mail") "https://github.com/shirakumo/radiance#27-mail")
  (("2.8" "profile") "https://github.com/shirakumo/radiance#28-profile")
  (("2.9" "rate") "https://github.com/shirakumo/radiance#29-rate")
  (("2.10" "server") "https://github.com/shirakumo/radiance#210-server")
  (("2.11" "session") "https://github.com/shirakumo/radiance#211-session")
  (("2.12" "user") "https://github.com/shirakumo/radiance#212-user")
  (("*DEBUGGER*" "RADIANCE-CORE:*DEBUGGER*") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:*DEBUGGER*" "RADIANCE-CORE:*DEBUGGER*")
  (("*DEFAULT-API-FORMAT*" "RADIANCE-CORE:*DEFAULT-API-FORMAT*") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:*DEFAULT-API-FORMAT*" "RADIANCE-CORE:*DEFAULT-API-FORMAT*")
  (("*DEFAULT-CONTENT-TYPE*" "RADIANCE-CORE:*DEFAULT-CONTENT-TYPE*") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:*DEFAULT-CONTENT-TYPE*" "RADIANCE-CORE:*DEFAULT-CONTENT-TYPE*")
  (("*DEFAULT-EXTERNAL-FORMAT*" "RADIANCE-CORE:*DEFAULT-EXTERNAL-FORMAT*") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:*DEFAULT-EXTERNAL-FORMAT*" "RADIANCE-CORE:*DEFAULT-EXTERNAL-FORMAT*")
  (("*ENVIRONMENT-ROOT*" "RADIANCE-CORE:*ENVIRONMENT-ROOT*") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:*ENVIRONMENT-ROOT*" "RADIANCE-CORE:*ENVIRONMENT-ROOT*")
  (("*MODULES-DIRECTORY*" "RADIANCE-CORE:*MODULES-DIRECTORY*") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:*MODULES-DIRECTORY*" "RADIANCE-CORE:*MODULES-DIRECTORY*")
  (("*RANDOM-STRING-CHARACTERS*" "RADIANCE-CORE:*RANDOM-STRING-CHARACTERS*") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:*RANDOM-STRING-CHARACTERS*" "RADIANCE-CORE:*RANDOM-STRING-CHARACTERS*")
  (("*REQUEST*" "RADIANCE-CORE:*REQUEST*") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:*REQUEST*" "RADIANCE-CORE:*REQUEST*")
  (("*RESPONSE*" "RADIANCE-CORE:*RESPONSE*") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:*RESPONSE*" "RADIANCE-CORE:*RESPONSE*")
  (("*STARTUP-TIME*" "RADIANCE-CORE:*STARTUP-TIME*") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:*STARTUP-TIME*" "RADIANCE-CORE:*STARTUP-TIME*")
  (("API-ENDPOINT" "RADIANCE-CORE:API-ENDPOINT") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:API-ENDPOINT" "RADIANCE-CORE:API-ENDPOINT")
  (("COOKIE" "RADIANCE-CORE:COOKIE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:COOKIE" "RADIANCE-CORE:COOKIE")
  (("DOCUMENTABLE" "RADIANCE-CORE:DOCUMENTABLE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DOCUMENTABLE" "RADIANCE-CORE:DOCUMENTABLE")
  (("MODULE" "RADIANCE-CORE:MODULE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:MODULE" "RADIANCE-CORE:MODULE")
  (("OPTION" "RADIANCE-CORE:OPTION") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:OPTION" "RADIANCE-CORE:OPTION")
  (("REQUEST" "RADIANCE-CORE:REQUEST") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:REQUEST" "RADIANCE-CORE:REQUEST")
  (("RESOURCE-TYPE" "RADIANCE-CORE:RESOURCE-TYPE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:RESOURCE-TYPE" "RADIANCE-CORE:RESOURCE-TYPE")
  (("RESPONSE" "RADIANCE-CORE:RESPONSE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:RESPONSE" "RADIANCE-CORE:RESPONSE")
  (("ROUTE" "RADIANCE-CORE:ROUTE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:ROUTE" "RADIANCE-CORE:ROUTE")
  (("URI" "RADIANCE-CORE:URI") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:URI" "RADIANCE-CORE:URI")
  (("URI-DISPATCHER" "RADIANCE-CORE:URI-DISPATCHER") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:URI-DISPATCHER" "RADIANCE-CORE:URI-DISPATCHER")
  (("VIRTUAL-MODULE" "RADIANCE-CORE:VIRTUAL-MODULE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:VIRTUAL-MODULE" "RADIANCE-CORE:VIRTUAL-MODULE")
  (("API" "RADIANCE-CORE:API") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:API" "RADIANCE-CORE:API")
  (("DOMAIN" "RADIANCE-CORE:DOMAIN") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DOMAIN" "RADIANCE-CORE:DOMAIN")
  (("PAGE" "RADIANCE-CORE:PAGE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:PAGE" "RADIANCE-CORE:PAGE")
  (("STATIC" "RADIANCE-CORE:STATIC") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:STATIC" "RADIANCE-CORE:STATIC")
  (("ACCESS" "RADIANCE-CORE:ACCESS") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:ACCESS" "RADIANCE-CORE:ACCESS")
  (("ACCESS" "RADIANCE-CORE:ACCESS") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:ACCESS" "RADIANCE-CORE:ACCESS")
  (("DOMAIN" "RADIANCE-CORE:DOMAIN") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DOMAIN" "RADIANCE-CORE:DOMAIN")
  (("DOMAIN" "RADIANCE-CORE:DOMAIN") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DOMAIN" "RADIANCE-CORE:DOMAIN")
  (("VIRTUAL-MODULE" "RADIANCE-CORE:VIRTUAL-MODULE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:VIRTUAL-MODULE" "RADIANCE-CORE:VIRTUAL-MODULE")
  (("VIRTUAL-MODULE" "RADIANCE-CORE:VIRTUAL-MODULE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:VIRTUAL-MODULE" "RADIANCE-CORE:VIRTUAL-MODULE")
  (("API-ARGUMENT-INVALID" "RADIANCE-CORE:API-ARGUMENT-INVALID") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:API-ARGUMENT-INVALID" "RADIANCE-CORE:API-ARGUMENT-INVALID")
  (("API-ARGUMENT-MISSING" "RADIANCE-CORE:API-ARGUMENT-MISSING") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:API-ARGUMENT-MISSING" "RADIANCE-CORE:API-ARGUMENT-MISSING")
  (("API-AUTH-ERROR" "RADIANCE-CORE:API-AUTH-ERROR") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:API-AUTH-ERROR" "RADIANCE-CORE:API-AUTH-ERROR")
  (("API-CALL-NOT-FOUND" "RADIANCE-CORE:API-CALL-NOT-FOUND") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:API-CALL-NOT-FOUND" "RADIANCE-CORE:API-CALL-NOT-FOUND")
  (("API-ERROR" "RADIANCE-CORE:API-ERROR") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:API-ERROR" "RADIANCE-CORE:API-ERROR")
  (("API-RESPONSE-EMPTY" "RADIANCE-CORE:API-RESPONSE-EMPTY") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:API-RESPONSE-EMPTY" "RADIANCE-CORE:API-RESPONSE-EMPTY")
  (("API-UNKNOWN-FORMAT" "RADIANCE-CORE:API-UNKNOWN-FORMAT") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:API-UNKNOWN-FORMAT" "RADIANCE-CORE:API-UNKNOWN-FORMAT")
  (("ENVIRONMENT-NOT-SET" "RADIANCE-CORE:ENVIRONMENT-NOT-SET") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:ENVIRONMENT-NOT-SET" "RADIANCE-CORE:ENVIRONMENT-NOT-SET")
  (("FILE-TO-SERVE-DOES-NOT-EXIST" "RADIANCE-CORE:FILE-TO-SERVE-DOES-NOT-EXIST") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:FILE-TO-SERVE-DOES-NOT-EXIST" "RADIANCE-CORE:FILE-TO-SERVE-DOES-NOT-EXIST")
  (("INTERFACE-IMPLEMENTATION-NOT-SET" "RADIANCE-CORE:INTERFACE-IMPLEMENTATION-NOT-SET") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:INTERFACE-IMPLEMENTATION-NOT-SET" "RADIANCE-CORE:INTERFACE-IMPLEMENTATION-NOT-SET")
  (("INTERNAL-ERROR" "RADIANCE-CORE:INTERNAL-ERROR") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:INTERNAL-ERROR" "RADIANCE-CORE:INTERNAL-ERROR")
  (("NO-SUCH-POST-PARAMETER" "RADIANCE-CORE:NO-SUCH-POST-PARAMETER") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:NO-SUCH-POST-PARAMETER" "RADIANCE-CORE:NO-SUCH-POST-PARAMETER")
  (("POST-PARAMETER-NOT-A-FILE" "RADIANCE-CORE:POST-PARAMETER-NOT-A-FILE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:POST-PARAMETER-NOT-A-FILE" "RADIANCE-CORE:POST-PARAMETER-NOT-A-FILE")
  (("RADIANCE-CONDITION" "RADIANCE-CORE:RADIANCE-CONDITION") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:RADIANCE-CONDITION" "RADIANCE-CORE:RADIANCE-CONDITION")
  (("REQUEST-DENIED" "RADIANCE-CORE:REQUEST-DENIED") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:REQUEST-DENIED" "RADIANCE-CORE:REQUEST-DENIED")
  (("REQUEST-EMPTY" "RADIANCE-CORE:REQUEST-EMPTY") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:REQUEST-EMPTY" "RADIANCE-CORE:REQUEST-EMPTY")
  (("REQUEST-ERROR" "RADIANCE-CORE:REQUEST-ERROR") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:REQUEST-ERROR" "RADIANCE-CORE:REQUEST-ERROR")
  (("REQUEST-NOT-FOUND" "RADIANCE-CORE:REQUEST-NOT-FOUND") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:REQUEST-NOT-FOUND" "RADIANCE-CORE:REQUEST-NOT-FOUND")
  (("UNPARSABLE-URI-STRING" "RADIANCE-CORE:UNPARSABLE-URI-STRING") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:UNPARSABLE-URI-STRING" "RADIANCE-CORE:UNPARSABLE-URI-STRING")
  (("API-ENDPOINT" "RADIANCE-CORE:API-ENDPOINT") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:API-ENDPOINT" "RADIANCE-CORE:API-ENDPOINT")
  (("API-FORMAT" "RADIANCE-CORE:API-FORMAT") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:API-FORMAT" "RADIANCE-CORE:API-FORMAT")
  (("ARGSLIST" "RADIANCE-CORE:ARGSLIST") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:ARGSLIST" "RADIANCE-CORE:ARGSLIST")
  (("CONTENT-TYPE" "RADIANCE-CORE:CONTENT-TYPE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:CONTENT-TYPE" "RADIANCE-CORE:CONTENT-TYPE")
  (("COOKIE" "RADIANCE-CORE:COOKIE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:COOKIE" "RADIANCE-CORE:COOKIE")
  (("COOKIES" "RADIANCE-CORE:COOKIES") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:COOKIES" "RADIANCE-CORE:COOKIES")
  (("DATA" "RADIANCE-CORE:DATA") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DATA" "RADIANCE-CORE:DATA")
  (("DIRECTION" "RADIANCE-CORE:DIRECTION") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DIRECTION" "RADIANCE-CORE:DIRECTION")
  (("DISPATCH-FUNCTION" "RADIANCE-CORE:DISPATCH-FUNCTION") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DISPATCH-FUNCTION" "RADIANCE-CORE:DISPATCH-FUNCTION")
  (("DOMAIN" "RADIANCE-CORE:DOMAIN") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DOMAIN" "RADIANCE-CORE:DOMAIN")
  (("DOMAINS" "RADIANCE-CORE:DOMAINS") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DOMAINS" "RADIANCE-CORE:DOMAINS")
  (("ENVIRONMENT" "RADIANCE-CORE:ENVIRONMENT") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:ENVIRONMENT" "RADIANCE-CORE:ENVIRONMENT")
  (("EXPANDER" "RADIANCE-CORE:EXPANDER") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:EXPANDER" "RADIANCE-CORE:EXPANDER")
  (("EXPIRES" "RADIANCE-CORE:EXPIRES") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:EXPIRES" "RADIANCE-CORE:EXPIRES")
  (("EXTERNAL-FORMAT" "RADIANCE-CORE:EXTERNAL-FORMAT") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:EXTERNAL-FORMAT" "RADIANCE-CORE:EXTERNAL-FORMAT")
  (("GET-DATA" "RADIANCE-CORE:GET-DATA") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:GET-DATA" "RADIANCE-CORE:GET-DATA")
  (("HANDLER" "RADIANCE-CORE:HANDLER") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:HANDLER" "RADIANCE-CORE:HANDLER")
  (("HEADER" "RADIANCE-CORE:HEADER") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:HEADER" "RADIANCE-CORE:HEADER")
  (("HEADERS" "RADIANCE-CORE:HEADERS") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:HEADERS" "RADIANCE-CORE:HEADERS")
  (("HTTP-METHOD" "RADIANCE-CORE:HTTP-METHOD") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:HTTP-METHOD" "RADIANCE-CORE:HTTP-METHOD")
  (("HTTP-ONLY" "RADIANCE-CORE:HTTP-ONLY") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:HTTP-ONLY" "RADIANCE-CORE:HTTP-ONLY")
  (("IMPLEMENTATION" "RADIANCE-CORE:IMPLEMENTATION") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:IMPLEMENTATION" "RADIANCE-CORE:IMPLEMENTATION")
  (("ISSUE-TIME" "RADIANCE-CORE:ISSUE-TIME") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:ISSUE-TIME" "RADIANCE-CORE:ISSUE-TIME")
  (("LOCATORS" "RADIANCE-CORE:LOCATORS") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:LOCATORS" "RADIANCE-CORE:LOCATORS")
  (("MATCHER" "RADIANCE-CORE:MATCHER") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:MATCHER" "RADIANCE-CORE:MATCHER")
  (("MCONFIG" "RADIANCE-CORE:MCONFIG") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:MCONFIG" "RADIANCE-CORE:MCONFIG")
  (("MESSAGE" "RADIANCE-CORE:MESSAGE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:MESSAGE" "RADIANCE-CORE:MESSAGE")
  (("MODULE-PERMISSIONS" "RADIANCE-CORE:MODULE-PERMISSIONS") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:MODULE-PERMISSIONS" "RADIANCE-CORE:MODULE-PERMISSIONS")
  (("MODULE-STORAGE" "RADIANCE-CORE:MODULE-STORAGE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:MODULE-STORAGE" "RADIANCE-CORE:MODULE-STORAGE")
  (("NAME" "RADIANCE-CORE:NAME") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:NAME" "RADIANCE-CORE:NAME")
  (("OPTION" "RADIANCE-CORE:OPTION") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:OPTION" "RADIANCE-CORE:OPTION")
  (("OPTION-TYPE" "RADIANCE-CORE:OPTION-TYPE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:OPTION-TYPE" "RADIANCE-CORE:OPTION-TYPE")
  (("PATH" "RADIANCE-CORE:PATH") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:PATH" "RADIANCE-CORE:PATH")
  (("PORT" "RADIANCE-CORE:PORT") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:PORT" "RADIANCE-CORE:PORT")
  (("POST-DATA" "RADIANCE-CORE:POST-DATA") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:POST-DATA" "RADIANCE-CORE:POST-DATA")
  (("PRIORITY" "RADIANCE-CORE:PRIORITY") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:PRIORITY" "RADIANCE-CORE:PRIORITY")
  (("REFERER" "RADIANCE-CORE:REFERER") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:REFERER" "RADIANCE-CORE:REFERER")
  (("REMOTE" "RADIANCE-CORE:REMOTE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:REMOTE" "RADIANCE-CORE:REMOTE")
  (("REQUEST-HANDLER" "RADIANCE-CORE:REQUEST-HANDLER") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:REQUEST-HANDLER" "RADIANCE-CORE:REQUEST-HANDLER")
  (("RESOURCE-LOCATOR" "RADIANCE-CORE:RESOURCE-LOCATOR") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:RESOURCE-LOCATOR" "RADIANCE-CORE:RESOURCE-LOCATOR")
  (("RESOURCE-TYPE" "RADIANCE-CORE:RESOURCE-TYPE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:RESOURCE-TYPE" "RADIANCE-CORE:RESOURCE-TYPE")
  (("RETURN-CODE" "RADIANCE-CORE:RETURN-CODE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:RETURN-CODE" "RADIANCE-CORE:RETURN-CODE")
  (("ROUTE" "RADIANCE-CORE:ROUTE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:ROUTE" "RADIANCE-CORE:ROUTE")
  (("SECURE" "RADIANCE-CORE:SECURE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:SECURE" "RADIANCE-CORE:SECURE")
  (("TRANSLATOR" "RADIANCE-CORE:TRANSLATOR") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:TRANSLATOR" "RADIANCE-CORE:TRANSLATOR")
  (("URI" "RADIANCE-CORE:URI") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:URI" "RADIANCE-CORE:URI")
  (("URI-DISPATCHER" "RADIANCE-CORE:URI-DISPATCHER") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:URI-DISPATCHER" "RADIANCE-CORE:URI-DISPATCHER")
  (("USER-AGENT" "RADIANCE-CORE:USER-AGENT") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:USER-AGENT" "RADIANCE-CORE:USER-AGENT")
  (("VALUE" "RADIANCE-CORE:VALUE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:VALUE" "RADIANCE-CORE:VALUE")
  (("VIRTUAL-MODULE-NAME" "RADIANCE-CORE:VIRTUAL-MODULE-NAME") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:VIRTUAL-MODULE-NAME" "RADIANCE-CORE:VIRTUAL-MODULE-NAME")
  (("*REQUEST*" "RADIANCE-CORE:*REQUEST*") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:*REQUEST*" "RADIANCE-CORE:*REQUEST*")
  (("*RESPONSE*" "RADIANCE-CORE:*RESPONSE*") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:*RESPONSE*" "RADIANCE-CORE:*RESPONSE*")
  (("ABORT-HANDLING" "RADIANCE-CORE:ABORT-HANDLING") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:ABORT-HANDLING" "RADIANCE-CORE:ABORT-HANDLING")
  (("ADD-DOMAIN" "RADIANCE-CORE:ADD-DOMAIN") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:ADD-DOMAIN" "RADIANCE-CORE:ADD-DOMAIN")
  (("API-OUTPUT" "RADIANCE-CORE:API-OUTPUT") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:API-OUTPUT" "RADIANCE-CORE:API-OUTPUT")
  (("CALL-API" "RADIANCE-CORE:CALL-API") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:CALL-API" "RADIANCE-CORE:CALL-API")
  (("CALL-API-REQUEST" "RADIANCE-CORE:CALL-API-REQUEST") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:CALL-API-REQUEST" "RADIANCE-CORE:CALL-API-REQUEST")
  (("CHECK-ENVIRONMENT" "RADIANCE-CORE:CHECK-ENVIRONMENT") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:CHECK-ENVIRONMENT" "RADIANCE-CORE:CHECK-ENVIRONMENT")
  (("COOKIE-HEADER" "RADIANCE-CORE:COOKIE-HEADER") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:COOKIE-HEADER" "RADIANCE-CORE:COOKIE-HEADER")
  (("COPY-URI" "RADIANCE-CORE:COPY-URI") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:COPY-URI" "RADIANCE-CORE:COPY-URI")
  (("CREATE-MODULE" "RADIANCE-CORE:CREATE-MODULE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:CREATE-MODULE" "RADIANCE-CORE:CREATE-MODULE")
  (("DEFAULTED-MCONFIG" "RADIANCE-CORE:DEFAULTED-MCONFIG") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DEFAULTED-MCONFIG" "RADIANCE-CORE:DEFAULTED-MCONFIG")
  (("DELETE-MODULE" "RADIANCE-CORE:DELETE-MODULE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DELETE-MODULE" "RADIANCE-CORE:DELETE-MODULE")
  (("DESCRIBE-MODULE" "RADIANCE-CORE:DESCRIBE-MODULE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DESCRIBE-MODULE" "RADIANCE-CORE:DESCRIBE-MODULE")
  (("DISPATCH" "RADIANCE-CORE:DISPATCH") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DISPATCH" "RADIANCE-CORE:DISPATCH")
  (("ENSURE-URI" "RADIANCE-CORE:ENSURE-URI") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:ENSURE-URI" "RADIANCE-CORE:ENSURE-URI")
  (("EXECUTE-REQUEST" "RADIANCE-CORE:EXECUTE-REQUEST") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:EXECUTE-REQUEST" "RADIANCE-CORE:EXECUTE-REQUEST")
  (("EXPAND-OPTIONS" "RADIANCE-CORE:EXPAND-OPTIONS") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:EXPAND-OPTIONS" "RADIANCE-CORE:EXPAND-OPTIONS")
  (("EXTERNAL-URI" "RADIANCE-CORE:EXTERNAL-URI") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:EXTERNAL-URI" "RADIANCE-CORE:EXTERNAL-URI")
  (("FILE" "RADIANCE-CORE:FILE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:FILE" "RADIANCE-CORE:FILE")
  (("FILE-SIZE" "RADIANCE-CORE:FILE-SIZE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:FILE-SIZE" "RADIANCE-CORE:FILE-SIZE")
  (("FIND-ALL-MODULES" "RADIANCE-CORE:FIND-ALL-MODULES") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:FIND-ALL-MODULES" "RADIANCE-CORE:FIND-ALL-MODULES")
  (("FIND-IMPLEMENTATION" "RADIANCE-CORE:FIND-IMPLEMENTATION") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:FIND-IMPLEMENTATION" "RADIANCE-CORE:FIND-IMPLEMENTATION")
  (("FORMAT-CLOCK-TIME" "RADIANCE-CORE:FORMAT-CLOCK-TIME") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:FORMAT-CLOCK-TIME" "RADIANCE-CORE:FORMAT-CLOCK-TIME")
  (("FORMAT-FANCY-DATE" "RADIANCE-CORE:FORMAT-FANCY-DATE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:FORMAT-FANCY-DATE" "RADIANCE-CORE:FORMAT-FANCY-DATE")
  (("FORMAT-HUMAN-DATE" "RADIANCE-CORE:FORMAT-HUMAN-DATE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:FORMAT-HUMAN-DATE" "RADIANCE-CORE:FORMAT-HUMAN-DATE")
  (("FORMAT-MACHINE-DATE" "RADIANCE-CORE:FORMAT-MACHINE-DATE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:FORMAT-MACHINE-DATE" "RADIANCE-CORE:FORMAT-MACHINE-DATE")
  (("FORMAT-RELATIVE-TIME" "RADIANCE-CORE:FORMAT-RELATIVE-TIME") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:FORMAT-RELATIVE-TIME" "RADIANCE-CORE:FORMAT-RELATIVE-TIME")
  (("FORMAT-TIME" "RADIANCE-CORE:FORMAT-TIME") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:FORMAT-TIME" "RADIANCE-CORE:FORMAT-TIME")
  (("FORMAT-URI" "RADIANCE-CORE:FORMAT-URI") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:FORMAT-URI" "RADIANCE-CORE:FORMAT-URI")
  (("GET-UNIX-TIME" "RADIANCE-CORE:GET-UNIX-TIME") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:GET-UNIX-TIME" "RADIANCE-CORE:GET-UNIX-TIME")
  (("GET-VAR" "RADIANCE-CORE:GET-VAR") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:GET-VAR" "RADIANCE-CORE:GET-VAR")
  (("HANDLE-CONDITION" "RADIANCE-CORE:HANDLE-CONDITION") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:HANDLE-CONDITION" "RADIANCE-CORE:HANDLE-CONDITION")
  (("IMPLEMENTS" "RADIANCE-CORE:IMPLEMENTS") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:IMPLEMENTS" "RADIANCE-CORE:IMPLEMENTS")
  (("INTERFACE" "RADIANCE-CORE:INTERFACE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:INTERFACE" "RADIANCE-CORE:INTERFACE")
  (("INTERFACE-P" "RADIANCE-CORE:INTERFACE-P") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:INTERFACE-P" "RADIANCE-CORE:INTERFACE-P")
  (("INTERNAL-URI" "RADIANCE-CORE:INTERNAL-URI") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:INTERNAL-URI" "RADIANCE-CORE:INTERNAL-URI")
  (("LIST-API-ENDPOINTS" "RADIANCE-CORE:LIST-API-ENDPOINTS") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:LIST-API-ENDPOINTS" "RADIANCE-CORE:LIST-API-ENDPOINTS")
  (("LIST-API-FORMATS" "RADIANCE-CORE:LIST-API-FORMATS") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:LIST-API-FORMATS" "RADIANCE-CORE:LIST-API-FORMATS")
  (("LIST-HOOKS" "RADIANCE-CORE:LIST-HOOKS") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:LIST-HOOKS" "RADIANCE-CORE:LIST-HOOKS")
  (("LIST-MODULES" "RADIANCE-CORE:LIST-MODULES") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:LIST-MODULES" "RADIANCE-CORE:LIST-MODULES")
  (("LIST-OPTIONS" "RADIANCE-CORE:LIST-OPTIONS") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:LIST-OPTIONS" "RADIANCE-CORE:LIST-OPTIONS")
  (("LIST-RESOURCE-TYPES" "RADIANCE-CORE:LIST-RESOURCE-TYPES") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:LIST-RESOURCE-TYPES" "RADIANCE-CORE:LIST-RESOURCE-TYPES")
  (("LIST-ROUTES" "RADIANCE-CORE:LIST-ROUTES") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:LIST-ROUTES" "RADIANCE-CORE:LIST-ROUTES")
  (("LIST-URI-DISPATCHERS" "RADIANCE-CORE:LIST-URI-DISPATCHERS") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:LIST-URI-DISPATCHERS" "RADIANCE-CORE:LIST-URI-DISPATCHERS")
  (("LOAD-IMPLEMENTATION" "RADIANCE-CORE:LOAD-IMPLEMENTATION") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:LOAD-IMPLEMENTATION" "RADIANCE-CORE:LOAD-IMPLEMENTATION")
  (("MAKE-RANDOM-STRING" "RADIANCE-CORE:MAKE-RANDOM-STRING") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:MAKE-RANDOM-STRING" "RADIANCE-CORE:MAKE-RANDOM-STRING")
  (("MAKE-URI" "RADIANCE-CORE:MAKE-URI") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:MAKE-URI" "RADIANCE-CORE:MAKE-URI")
  (("MAKE-URL" "RADIANCE-CORE:MAKE-URL") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:MAKE-URL" "RADIANCE-CORE:MAKE-URL")
  (("MCONFIG-PATHNAME" "RADIANCE-CORE:MCONFIG-PATHNAME") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:MCONFIG-PATHNAME" "RADIANCE-CORE:MCONFIG-PATHNAME")
  (("MCONFIG-STORAGE" "RADIANCE-CORE:MCONFIG-STORAGE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:MCONFIG-STORAGE" "RADIANCE-CORE:MCONFIG-STORAGE")
  (("MERGE-URIS" "RADIANCE-CORE:MERGE-URIS") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:MERGE-URIS" "RADIANCE-CORE:MERGE-URIS")
  (("MODULE" "RADIANCE-CORE:MODULE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:MODULE" "RADIANCE-CORE:MODULE")
  (("MODULE-API-ENDPOINTS" "RADIANCE-CORE:MODULE-API-ENDPOINTS") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:MODULE-API-ENDPOINTS" "RADIANCE-CORE:MODULE-API-ENDPOINTS")
  (("MODULE-DEPENDENCIES" "RADIANCE-CORE:MODULE-DEPENDENCIES") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:MODULE-DEPENDENCIES" "RADIANCE-CORE:MODULE-DEPENDENCIES")
  (("MODULE-DOMAIN" "RADIANCE-CORE:MODULE-DOMAIN") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:MODULE-DOMAIN" "RADIANCE-CORE:MODULE-DOMAIN")
  (("MODULE-IDENTIFIER" "RADIANCE-CORE:MODULE-IDENTIFIER") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:MODULE-IDENTIFIER" "RADIANCE-CORE:MODULE-IDENTIFIER")
  (("MODULE-NAME" "RADIANCE-CORE:MODULE-NAME") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:MODULE-NAME" "RADIANCE-CORE:MODULE-NAME")
  (("MODULE-P" "RADIANCE-CORE:MODULE-P") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:MODULE-P" "RADIANCE-CORE:MODULE-P")
  (("MODULE-PAGES" "RADIANCE-CORE:MODULE-PAGES") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:MODULE-PAGES" "RADIANCE-CORE:MODULE-PAGES")
  (("MODULE-REQUIRED-INTERFACES" "RADIANCE-CORE:MODULE-REQUIRED-INTERFACES") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:MODULE-REQUIRED-INTERFACES" "RADIANCE-CORE:MODULE-REQUIRED-INTERFACES")
  (("MODULE-REQUIRED-SYSTEMS" "RADIANCE-CORE:MODULE-REQUIRED-SYSTEMS") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:MODULE-REQUIRED-SYSTEMS" "RADIANCE-CORE:MODULE-REQUIRED-SYSTEMS")
  (("MODULE-STORAGE-REMOVE" "RADIANCE-CORE:MODULE-STORAGE-REMOVE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:MODULE-STORAGE-REMOVE" "RADIANCE-CORE:MODULE-STORAGE-REMOVE")
  (("PARSE-PATH-SAFELY" "RADIANCE-CORE:PARSE-PATH-SAFELY") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:PARSE-PATH-SAFELY" "RADIANCE-CORE:PARSE-PATH-SAFELY")
  (("PARSE-URI" "RADIANCE-CORE:PARSE-URI") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:PARSE-URI" "RADIANCE-CORE:PARSE-URI")
  (("POST-VAR" "RADIANCE-CORE:POST-VAR") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:POST-VAR" "RADIANCE-CORE:POST-VAR")
  (("POST/GET" "RADIANCE-CORE:POST/GET") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:POST/GET" "RADIANCE-CORE:POST/GET")
  (("REDIRECT" "RADIANCE-CORE:REDIRECT") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:REDIRECT" "RADIANCE-CORE:REDIRECT")
  (("RELOAD-ENVIRONMENT" "RADIANCE-CORE:RELOAD-ENVIRONMENT") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:RELOAD-ENVIRONMENT" "RADIANCE-CORE:RELOAD-ENVIRONMENT")
  (("REMMCONFIG" "RADIANCE-CORE:REMMCONFIG") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:REMMCONFIG" "RADIANCE-CORE:REMMCONFIG")
  (("REMOVE-API-ENDPOINT" "RADIANCE-CORE:REMOVE-API-ENDPOINT") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:REMOVE-API-ENDPOINT" "RADIANCE-CORE:REMOVE-API-ENDPOINT")
  (("REMOVE-API-FORMAT" "RADIANCE-CORE:REMOVE-API-FORMAT") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:REMOVE-API-FORMAT" "RADIANCE-CORE:REMOVE-API-FORMAT")
  (("REMOVE-DOMAIN" "RADIANCE-CORE:REMOVE-DOMAIN") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:REMOVE-DOMAIN" "RADIANCE-CORE:REMOVE-DOMAIN")
  (("REMOVE-HOOK" "RADIANCE-CORE:REMOVE-HOOK") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:REMOVE-HOOK" "RADIANCE-CORE:REMOVE-HOOK")
  (("REMOVE-OPTION" "RADIANCE-CORE:REMOVE-OPTION") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:REMOVE-OPTION" "RADIANCE-CORE:REMOVE-OPTION")
  (("REMOVE-PAGE" "RADIANCE-CORE:REMOVE-PAGE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:REMOVE-PAGE" "RADIANCE-CORE:REMOVE-PAGE")
  (("REMOVE-RESOURCE-TYPE" "RADIANCE-CORE:REMOVE-RESOURCE-TYPE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:REMOVE-RESOURCE-TYPE" "RADIANCE-CORE:REMOVE-RESOURCE-TYPE")
  (("REMOVE-ROUTE" "RADIANCE-CORE:REMOVE-ROUTE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:REMOVE-ROUTE" "RADIANCE-CORE:REMOVE-ROUTE")
  (("REMOVE-TRIGGER" "RADIANCE-CORE:REMOVE-TRIGGER") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:REMOVE-TRIGGER" "RADIANCE-CORE:REMOVE-TRIGGER")
  (("REMOVE-URI-DISPATCHER" "RADIANCE-CORE:REMOVE-URI-DISPATCHER") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:REMOVE-URI-DISPATCHER" "RADIANCE-CORE:REMOVE-URI-DISPATCHER")
  (("RENDER-ERROR-PAGE" "RADIANCE-CORE:RENDER-ERROR-PAGE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:RENDER-ERROR-PAGE" "RADIANCE-CORE:RENDER-ERROR-PAGE")
  (("REPRESENT-URI" "RADIANCE-CORE:REPRESENT-URI") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:REPRESENT-URI" "RADIANCE-CORE:REPRESENT-URI")
  (("REQUEST" "RADIANCE-CORE:REQUEST") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:REQUEST" "RADIANCE-CORE:REQUEST")
  (("REQUEST-RUN-TIME" "RADIANCE-CORE:REQUEST-RUN-TIME") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:REQUEST-RUN-TIME" "RADIANCE-CORE:REQUEST-RUN-TIME")
  (("RESET-INTERFACE" "RADIANCE-CORE:RESET-INTERFACE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:RESET-INTERFACE" "RADIANCE-CORE:RESET-INTERFACE")
  (("RESOLVE-BASE" "RADIANCE-CORE:RESOLVE-BASE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:RESOLVE-BASE" "RADIANCE-CORE:RESOLVE-BASE")
  (("RESOURCE" "RADIANCE-CORE:RESOURCE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:RESOURCE" "RADIANCE-CORE:RESOURCE")
  (("SEND" "MAIL:SEND") "https://shirakumo.github.io/radiance/#MAIL:SEND" "MAIL:SEND")
  (("SERVE-FILE" "RADIANCE-CORE:SERVE-FILE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:SERVE-FILE" "RADIANCE-CORE:SERVE-FILE")
  (("SHUTDOWN" "RADIANCE-CORE:SHUTDOWN") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:SHUTDOWN" "RADIANCE-CORE:SHUTDOWN")
  (("STARTED-P" "RADIANCE-CORE:STARTED-P") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:STARTED-P" "RADIANCE-CORE:STARTED-P")
  (("STARTUP" "RADIANCE-CORE:STARTUP") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:STARTUP" "RADIANCE-CORE:STARTUP")
  (("STATIC-FILE" "RADIANCE-CORE:STATIC-FILE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:STATIC-FILE" "RADIANCE-CORE:STATIC-FILE")
  (("TEMPLATE-FILE" "RADIANCE-CORE:TEMPLATE-FILE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:TEMPLATE-FILE" "RADIANCE-CORE:TEMPLATE-FILE")
  (("TRIGGER" "RADIANCE-CORE:TRIGGER") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:TRIGGER" "RADIANCE-CORE:TRIGGER")
  (("UNIVERSAL-TO-UNIX-TIME" "RADIANCE-CORE:UNIVERSAL-TO-UNIX-TIME") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:UNIVERSAL-TO-UNIX-TIME" "RADIANCE-CORE:UNIVERSAL-TO-UNIX-TIME")
  (("UNIX-TO-UNIVERSAL-TIME" "RADIANCE-CORE:UNIX-TO-UNIVERSAL-TIME") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:UNIX-TO-UNIVERSAL-TIME" "RADIANCE-CORE:UNIX-TO-UNIVERSAL-TIME")
  (("UPTIME" "RADIANCE-CORE:UPTIME") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:UPTIME" "RADIANCE-CORE:UPTIME")
  (("URI-DISPATCHER>" "RADIANCE-CORE:URI-DISPATCHER>") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:URI-DISPATCHER>" "RADIANCE-CORE:URI-DISPATCHER>")
  (("URI-MATCHES" "RADIANCE-CORE:URI-MATCHES") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:URI-MATCHES" "RADIANCE-CORE:URI-MATCHES")
  (("URI-STRING" "RADIANCE-CORE:URI-STRING") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:URI-STRING" "RADIANCE-CORE:URI-STRING")
  (("URI-TO-URL" "RADIANCE-CORE:URI-TO-URL") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:URI-TO-URL" "RADIANCE-CORE:URI-TO-URL")
  (("URI<" "RADIANCE-CORE:URI<") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:URI<" "RADIANCE-CORE:URI<")
  (("URI=" "RADIANCE-CORE:URI=") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:URI=" "RADIANCE-CORE:URI=")
  (("URI>" "RADIANCE-CORE:URI>") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:URI>" "RADIANCE-CORE:URI>")
  (("URL-ENCODE" "RADIANCE-CORE:URL-ENCODE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:URL-ENCODE" "RADIANCE-CORE:URL-ENCODE")
  (("VIRTUAL-MODULE" "RADIANCE-CORE:VIRTUAL-MODULE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:VIRTUAL-MODULE" "RADIANCE-CORE:VIRTUAL-MODULE")
  (("" "RADIANCE-CORE:") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:" "RADIANCE-CORE:")
  (("API" "RADIANCE-CORE:API") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:API" "RADIANCE-CORE:API")
  (("FAVICON" "RADIANCE-CORE:FAVICON") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:FAVICON" "RADIANCE-CORE:FAVICON")
  (("ROBOTS" "RADIANCE-CORE:ROBOTS") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:ROBOTS" "RADIANCE-CORE:ROBOTS")
  (("STATIC" "RADIANCE-CORE:STATIC") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:STATIC" "RADIANCE-CORE:STATIC")
  (("API-SERIALIZE" "RADIANCE-CORE:API-SERIALIZE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:API-SERIALIZE" "RADIANCE-CORE:API-SERIALIZE")
  (("@STATIC" "RADIANCE-CORE:@STATIC") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:@STATIC" "RADIANCE-CORE:@STATIC")
  (("@TEMPLATE" "RADIANCE-CORE:@TEMPLATE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:@TEMPLATE" "RADIANCE-CORE:@TEMPLATE")
  (("API-ERROR" "RADIANCE-CORE:API-ERROR") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:API-ERROR" "RADIANCE-CORE:API-ERROR")
  (("CONFIG" "RADIANCE-CORE:CONFIG") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:CONFIG" "RADIANCE-CORE:CONFIG")
  (("CURRENT-MODULE" "RADIANCE-CORE:CURRENT-MODULE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:CURRENT-MODULE" "RADIANCE-CORE:CURRENT-MODULE")
  (("DEFAULTED-CONFIG" "RADIANCE-CORE:DEFAULTED-CONFIG") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DEFAULTED-CONFIG" "RADIANCE-CORE:DEFAULTED-CONFIG")
  (("DEFINE-API" "RADIANCE-CORE:DEFINE-API") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DEFINE-API" "RADIANCE-CORE:DEFINE-API")
  (("DEFINE-API-FORMAT" "RADIANCE-CORE:DEFINE-API-FORMAT") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DEFINE-API-FORMAT" "RADIANCE-CORE:DEFINE-API-FORMAT")
  (("DEFINE-DOCUMENTABLE" "RADIANCE-CORE:DEFINE-DOCUMENTABLE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DEFINE-DOCUMENTABLE" "RADIANCE-CORE:DEFINE-DOCUMENTABLE")
  (("DEFINE-HOOK" "RADIANCE-CORE:DEFINE-HOOK") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DEFINE-HOOK" "RADIANCE-CORE:DEFINE-HOOK")
  (("DEFINE-HOOK-SWITCH" "RADIANCE-CORE:DEFINE-HOOK-SWITCH") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DEFINE-HOOK-SWITCH" "RADIANCE-CORE:DEFINE-HOOK-SWITCH")
  (("DEFINE-IMPLEMENT-TRIGGER" "RADIANCE-CORE:DEFINE-IMPLEMENT-TRIGGER") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DEFINE-IMPLEMENT-TRIGGER" "RADIANCE-CORE:DEFINE-IMPLEMENT-TRIGGER")
  (("DEFINE-INTERFACE" "RADIANCE-CORE:DEFINE-INTERFACE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DEFINE-INTERFACE" "RADIANCE-CORE:DEFINE-INTERFACE")
  (("DEFINE-INTERFACE-EXTENSION" "RADIANCE-CORE:DEFINE-INTERFACE-EXTENSION") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DEFINE-INTERFACE-EXTENSION" "RADIANCE-CORE:DEFINE-INTERFACE-EXTENSION")
  (("DEFINE-MATCHING-ROUTE" "RADIANCE-CORE:DEFINE-MATCHING-ROUTE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DEFINE-MATCHING-ROUTE" "RADIANCE-CORE:DEFINE-MATCHING-ROUTE")
  (("DEFINE-MODULE" "RADIANCE-CORE:DEFINE-MODULE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DEFINE-MODULE" "RADIANCE-CORE:DEFINE-MODULE")
  (("DEFINE-MODULE-EXTENSION" "RADIANCE-CORE:DEFINE-MODULE-EXTENSION") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DEFINE-MODULE-EXTENSION" "RADIANCE-CORE:DEFINE-MODULE-EXTENSION")
  (("DEFINE-OPTION" "RADIANCE-CORE:DEFINE-OPTION") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DEFINE-OPTION" "RADIANCE-CORE:DEFINE-OPTION")
  (("DEFINE-PAGE" "RADIANCE-CORE:DEFINE-PAGE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DEFINE-PAGE" "RADIANCE-CORE:DEFINE-PAGE")
  (("DEFINE-RESOURCE-LOCATOR" "RADIANCE-CORE:DEFINE-RESOURCE-LOCATOR") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DEFINE-RESOURCE-LOCATOR" "RADIANCE-CORE:DEFINE-RESOURCE-LOCATOR")
  (("DEFINE-RESOURCE-TYPE" "RADIANCE-CORE:DEFINE-RESOURCE-TYPE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DEFINE-RESOURCE-TYPE" "RADIANCE-CORE:DEFINE-RESOURCE-TYPE")
  (("DEFINE-ROUTE" "RADIANCE-CORE:DEFINE-ROUTE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DEFINE-ROUTE" "RADIANCE-CORE:DEFINE-ROUTE")
  (("DEFINE-STRING-ROUTE" "RADIANCE-CORE:DEFINE-STRING-ROUTE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DEFINE-STRING-ROUTE" "RADIANCE-CORE:DEFINE-STRING-ROUTE")
  (("DEFINE-TARGET-ROUTE" "RADIANCE-CORE:DEFINE-TARGET-ROUTE") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DEFINE-TARGET-ROUTE" "RADIANCE-CORE:DEFINE-TARGET-ROUTE")
  (("DEFINE-TRIGGER" "RADIANCE-CORE:DEFINE-TRIGGER") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DEFINE-TRIGGER" "RADIANCE-CORE:DEFINE-TRIGGER")
  (("DEFINE-URI-DISPATCHER" "RADIANCE-CORE:DEFINE-URI-DISPATCHER") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:DEFINE-URI-DISPATCHER" "RADIANCE-CORE:DEFINE-URI-DISPATCHER")
  (("OR*" "RADIANCE-CORE:OR*") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:OR*" "RADIANCE-CORE:OR*")
  (("PERM" "RADIANCE-CORE:PERM") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:PERM" "RADIANCE-CORE:PERM")
  (("REMCONFIG" "RADIANCE-CORE:REMCONFIG") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:REMCONFIG" "RADIANCE-CORE:REMCONFIG")
  (("WITH-ACTIONS" "RADIANCE-CORE:WITH-ACTIONS") "https://shirakumo.github.io/radiance/#RADIANCE-CORE:WITH-ACTIONS" "RADIANCE-CORE:WITH-ACTIONS")
  (("*IMPLEMENTATION*" "ADMIN:*IMPLEMENTATION*") "https://shirakumo.github.io/radiance/#ADMIN:*IMPLEMENTATION*" "ADMIN:*IMPLEMENTATION*")
  (("PAGE" "ADMIN:PAGE") "https://shirakumo.github.io/radiance/#ADMIN:PAGE" "ADMIN:PAGE")
  (("ACCESS" "ADMIN:ACCESS") "https://shirakumo.github.io/radiance/#ADMIN:ACCESS" "ADMIN:ACCESS")
  (("IMPLEMENTATION" "ADMIN:IMPLEMENTATION") "https://shirakumo.github.io/radiance/#ADMIN:IMPLEMENTATION" "ADMIN:IMPLEMENTATION")
  (("LIST-PANELS" "ADMIN:LIST-PANELS") "https://shirakumo.github.io/radiance/#ADMIN:LIST-PANELS" "ADMIN:LIST-PANELS")
  (("REMOVE-PANEL" "ADMIN:REMOVE-PANEL") "https://shirakumo.github.io/radiance/#ADMIN:REMOVE-PANEL" "ADMIN:REMOVE-PANEL")
  (("DEFINE-PANEL" "ADMIN:DEFINE-PANEL") "https://shirakumo.github.io/radiance/#ADMIN:DEFINE-PANEL" "ADMIN:DEFINE-PANEL")
  (("*IMPLEMENTATION*" "AUTH:*IMPLEMENTATION*") "https://shirakumo.github.io/radiance/#AUTH:*IMPLEMENTATION*" "AUTH:*IMPLEMENTATION*")
  (("*LOGIN-TIMEOUT*" "AUTH:*LOGIN-TIMEOUT*") "https://shirakumo.github.io/radiance/#AUTH:*LOGIN-TIMEOUT*" "AUTH:*LOGIN-TIMEOUT*")
  (("PAGE" "AUTH:PAGE") "https://shirakumo.github.io/radiance/#AUTH:PAGE" "AUTH:PAGE")
  (("IMPLEMENTATION" "AUTH:IMPLEMENTATION") "https://shirakumo.github.io/radiance/#AUTH:IMPLEMENTATION" "AUTH:IMPLEMENTATION")
  (("ASSOCIATE" "AUTH:ASSOCIATE") "https://shirakumo.github.io/radiance/#AUTH:ASSOCIATE" "AUTH:ASSOCIATE")
  (("CURRENT" "AUTH:CURRENT") "https://shirakumo.github.io/radiance/#AUTH:CURRENT" "AUTH:CURRENT")
  (("*IMPLEMENTATION*" "BAN:*IMPLEMENTATION*") "https://shirakumo.github.io/radiance/#BAN:*IMPLEMENTATION*" "BAN:*IMPLEMENTATION*")
  (("IMPLEMENTATION" "BAN:IMPLEMENTATION") "https://shirakumo.github.io/radiance/#BAN:IMPLEMENTATION" "BAN:IMPLEMENTATION")
  (("JAIL" "BAN:JAIL") "https://shirakumo.github.io/radiance/#BAN:JAIL" "BAN:JAIL")
  (("JAIL-TIME" "BAN:JAIL-TIME") "https://shirakumo.github.io/radiance/#BAN:JAIL-TIME" "BAN:JAIL-TIME")
  (("LIST" "BAN:LIST") "https://shirakumo.github.io/radiance/#BAN:LIST" "BAN:LIST")
  (("RELEASE" "BAN:RELEASE") "https://shirakumo.github.io/radiance/#BAN:RELEASE" "BAN:RELEASE")
  (("*IMPLEMENTATION*" "CACHE:*IMPLEMENTATION*") "https://shirakumo.github.io/radiance/#CACHE:*IMPLEMENTATION*" "CACHE:*IMPLEMENTATION*")
  (("IMPLEMENTATION" "CACHE:IMPLEMENTATION") "https://shirakumo.github.io/radiance/#CACHE:IMPLEMENTATION" "CACHE:IMPLEMENTATION")
  (("GET" "CACHE:GET") "https://shirakumo.github.io/radiance/#CACHE:GET" "CACHE:GET")
  (("RENEW" "CACHE:RENEW") "https://shirakumo.github.io/radiance/#CACHE:RENEW" "CACHE:RENEW")
  (("WITH-CACHE" "CACHE:WITH-CACHE") "https://shirakumo.github.io/radiance/#CACHE:WITH-CACHE" "CACHE:WITH-CACHE")
  (("*IMPLEMENTATION*" "DATABASE:*IMPLEMENTATION*") "https://shirakumo.github.io/radiance/#DATABASE:*IMPLEMENTATION*" "DATABASE:*IMPLEMENTATION*")
  (("COLLECTION-ALREADY-EXISTS" "DATABASE:COLLECTION-ALREADY-EXISTS") "https://shirakumo.github.io/radiance/#DATABASE:COLLECTION-ALREADY-EXISTS" "DATABASE:COLLECTION-ALREADY-EXISTS")
  (("COLLECTION-CONDITION" "DATABASE:COLLECTION-CONDITION") "https://shirakumo.github.io/radiance/#DATABASE:COLLECTION-CONDITION" "DATABASE:COLLECTION-CONDITION")
  (("CONDITION" "DATABASE:CONDITION") "https://shirakumo.github.io/radiance/#DATABASE:CONDITION" "DATABASE:CONDITION")
  (("CONNECTION-ALREADY-OPEN" "DATABASE:CONNECTION-ALREADY-OPEN") "https://shirakumo.github.io/radiance/#DATABASE:CONNECTION-ALREADY-OPEN" "DATABASE:CONNECTION-ALREADY-OPEN")
  (("CONNECTION-FAILED" "DATABASE:CONNECTION-FAILED") "https://shirakumo.github.io/radiance/#DATABASE:CONNECTION-FAILED" "DATABASE:CONNECTION-FAILED")
  (("ID" "DATABASE:ID") "https://shirakumo.github.io/radiance/#DATABASE:ID" "DATABASE:ID")
  (("INVALID-COLLECTION" "DATABASE:INVALID-COLLECTION") "https://shirakumo.github.io/radiance/#DATABASE:INVALID-COLLECTION" "DATABASE:INVALID-COLLECTION")
  (("INVALID-FIELD" "DATABASE:INVALID-FIELD") "https://shirakumo.github.io/radiance/#DATABASE:INVALID-FIELD" "DATABASE:INVALID-FIELD")
  (("ID" "DATABASE:ID") "https://shirakumo.github.io/radiance/#DATABASE:ID" "DATABASE:ID")
  (("IMPLEMENTATION" "DATABASE:IMPLEMENTATION") "https://shirakumo.github.io/radiance/#DATABASE:IMPLEMENTATION" "DATABASE:IMPLEMENTATION")
  (("COLLECTION-EXISTS-P" "DATABASE:COLLECTION-EXISTS-P") "https://shirakumo.github.io/radiance/#DATABASE:COLLECTION-EXISTS-P" "DATABASE:COLLECTION-EXISTS-P")
  (("COLLECTIONS" "DATABASE:COLLECTIONS") "https://shirakumo.github.io/radiance/#DATABASE:COLLECTIONS" "DATABASE:COLLECTIONS")
  (("CONNECT" "DATABASE:CONNECT") "https://shirakumo.github.io/radiance/#DATABASE:CONNECT" "DATABASE:CONNECT")
  (("CONNECTED-P" "DATABASE:CONNECTED-P") "https://shirakumo.github.io/radiance/#DATABASE:CONNECTED-P" "DATABASE:CONNECTED-P")
  (("COUNT" "DATABASE:COUNT") "https://shirakumo.github.io/radiance/#DATABASE:COUNT" "DATABASE:COUNT")
  (("CREATE" "DATABASE:CREATE") "https://shirakumo.github.io/radiance/#DATABASE:CREATE" "DATABASE:CREATE")
  (("DISCONNECT" "DATABASE:DISCONNECT") "https://shirakumo.github.io/radiance/#DATABASE:DISCONNECT" "DATABASE:DISCONNECT")
  (("DROP" "DATABASE:DROP") "https://shirakumo.github.io/radiance/#DATABASE:DROP" "DATABASE:DROP")
  (("EMPTY" "DATABASE:EMPTY") "https://shirakumo.github.io/radiance/#DATABASE:EMPTY" "DATABASE:EMPTY")
  (("ENSURE-ID" "DATABASE:ENSURE-ID") "https://shirakumo.github.io/radiance/#DATABASE:ENSURE-ID" "DATABASE:ENSURE-ID")
  (("INSERT" "DATABASE:INSERT") "https://shirakumo.github.io/radiance/#DATABASE:INSERT" "DATABASE:INSERT")
  (("ITERATE" "DATABASE:ITERATE") "https://shirakumo.github.io/radiance/#DATABASE:ITERATE" "DATABASE:ITERATE")
  (("REMOVE" "DATABASE:REMOVE") "https://shirakumo.github.io/radiance/#DATABASE:REMOVE" "DATABASE:REMOVE")
  (("SELECT" "DATABASE:SELECT") "https://shirakumo.github.io/radiance/#DATABASE:SELECT" "DATABASE:SELECT")
  (("STRUCTURE" "DATABASE:STRUCTURE") "https://shirakumo.github.io/radiance/#DATABASE:STRUCTURE" "DATABASE:STRUCTURE")
  (("UPDATE" "DATABASE:UPDATE") "https://shirakumo.github.io/radiance/#DATABASE:UPDATE" "DATABASE:UPDATE")
  (("QUERY" "DATABASE:QUERY") "https://shirakumo.github.io/radiance/#DATABASE:QUERY" "DATABASE:QUERY")
  (("WITH-TRANSACTION" "DATABASE:WITH-TRANSACTION") "https://shirakumo.github.io/radiance/#DATABASE:WITH-TRANSACTION" "DATABASE:WITH-TRANSACTION")
  (("*IMPLEMENTATION*" "LOGGER:*IMPLEMENTATION*") "https://shirakumo.github.io/radiance/#LOGGER:*IMPLEMENTATION*" "LOGGER:*IMPLEMENTATION*")
  (("IMPLEMENTATION" "LOGGER:IMPLEMENTATION") "https://shirakumo.github.io/radiance/#LOGGER:IMPLEMENTATION" "LOGGER:IMPLEMENTATION")
  (("DEBUG" "LOGGER:DEBUG") "https://shirakumo.github.io/radiance/#LOGGER:DEBUG" "LOGGER:DEBUG")
  (("ERROR" "LOGGER:ERROR") "https://shirakumo.github.io/radiance/#LOGGER:ERROR" "LOGGER:ERROR")
  (("FATAL" "LOGGER:FATAL") "https://shirakumo.github.io/radiance/#LOGGER:FATAL" "LOGGER:FATAL")
  (("INFO" "LOGGER:INFO") "https://shirakumo.github.io/radiance/#LOGGER:INFO" "LOGGER:INFO")
  (("LOG" "LOGGER:LOG") "https://shirakumo.github.io/radiance/#LOGGER:LOG" "LOGGER:LOG")
  (("SEVERE" "LOGGER:SEVERE") "https://shirakumo.github.io/radiance/#LOGGER:SEVERE" "LOGGER:SEVERE")
  (("TRACE" "LOGGER:TRACE") "https://shirakumo.github.io/radiance/#LOGGER:TRACE" "LOGGER:TRACE")
  (("WARN" "LOGGER:WARN") "https://shirakumo.github.io/radiance/#LOGGER:WARN" "LOGGER:WARN")
  (("*IMPLEMENTATION*" "PROFILE:*IMPLEMENTATION*") "https://shirakumo.github.io/radiance/#PROFILE:*IMPLEMENTATION*" "PROFILE:*IMPLEMENTATION*")
  (("PAGE" "PROFILE:PAGE") "https://shirakumo.github.io/radiance/#PROFILE:PAGE" "PROFILE:PAGE")
  (("ACCESS" "PROFILE:ACCESS") "https://shirakumo.github.io/radiance/#PROFILE:ACCESS" "PROFILE:ACCESS")
  (("IMPLEMENTATION" "PROFILE:IMPLEMENTATION") "https://shirakumo.github.io/radiance/#PROFILE:IMPLEMENTATION" "PROFILE:IMPLEMENTATION")
  (("ADD-FIELD" "PROFILE:ADD-FIELD") "https://shirakumo.github.io/radiance/#PROFILE:ADD-FIELD" "PROFILE:ADD-FIELD")
  (("AVATAR" "PROFILE:AVATAR") "https://shirakumo.github.io/radiance/#PROFILE:AVATAR" "PROFILE:AVATAR")
  (("FIELDS" "PROFILE:FIELDS") "https://shirakumo.github.io/radiance/#PROFILE:FIELDS" "PROFILE:FIELDS")
  (("LIST-PANELS" "PROFILE:LIST-PANELS") "https://shirakumo.github.io/radiance/#PROFILE:LIST-PANELS" "PROFILE:LIST-PANELS")
  (("NAME" "PROFILE:NAME") "https://shirakumo.github.io/radiance/#PROFILE:NAME" "PROFILE:NAME")
  (("REMOVE-FIELD" "PROFILE:REMOVE-FIELD") "https://shirakumo.github.io/radiance/#PROFILE:REMOVE-FIELD" "PROFILE:REMOVE-FIELD")
  (("REMOVE-PANEL" "PROFILE:REMOVE-PANEL") "https://shirakumo.github.io/radiance/#PROFILE:REMOVE-PANEL" "PROFILE:REMOVE-PANEL")
  (("DEFINE-PANEL" "PROFILE:DEFINE-PANEL") "https://shirakumo.github.io/radiance/#PROFILE:DEFINE-PANEL" "PROFILE:DEFINE-PANEL")
  (("*IMPLEMENTATION*" "RATE:*IMPLEMENTATION*") "https://shirakumo.github.io/radiance/#RATE:*IMPLEMENTATION*" "RATE:*IMPLEMENTATION*")
  (("IMPLEMENTATION" "RATE:IMPLEMENTATION") "https://shirakumo.github.io/radiance/#RATE:IMPLEMENTATION" "RATE:IMPLEMENTATION")
  (("LEFT" "RATE:LEFT") "https://shirakumo.github.io/radiance/#RATE:LEFT" "RATE:LEFT")
  (("DEFINE-LIMIT" "RATE:DEFINE-LIMIT") "https://shirakumo.github.io/radiance/#RATE:DEFINE-LIMIT" "RATE:DEFINE-LIMIT")
  (("WITH-LIMITATION" "RATE:WITH-LIMITATION") "https://shirakumo.github.io/radiance/#RATE:WITH-LIMITATION" "RATE:WITH-LIMITATION")
  (("*IMPLEMENTATION*" "SERVER:*IMPLEMENTATION*") "https://shirakumo.github.io/radiance/#SERVER:*IMPLEMENTATION*" "SERVER:*IMPLEMENTATION*")
  (("IMPLEMENTATION" "SERVER:IMPLEMENTATION") "https://shirakumo.github.io/radiance/#SERVER:IMPLEMENTATION" "SERVER:IMPLEMENTATION")
  (("LISTENERS" "SERVER:LISTENERS") "https://shirakumo.github.io/radiance/#SERVER:LISTENERS" "SERVER:LISTENERS")
  (("START" "SERVER:START") "https://shirakumo.github.io/radiance/#SERVER:START" "SERVER:START")
  (("STOP" "SERVER:STOP") "https://shirakumo.github.io/radiance/#SERVER:STOP" "SERVER:STOP")
  (("*DEFAULT-TIMEOUT*" "SESSION:*DEFAULT-TIMEOUT*") "https://shirakumo.github.io/radiance/#SESSION:*DEFAULT-TIMEOUT*" "SESSION:*DEFAULT-TIMEOUT*")
  (("*IMPLEMENTATION*" "SESSION:*IMPLEMENTATION*") "https://shirakumo.github.io/radiance/#SESSION:*IMPLEMENTATION*" "SESSION:*IMPLEMENTATION*")
  (("SESSION" "SESSION:SESSION") "https://shirakumo.github.io/radiance/#SESSION:SESSION" "SESSION:SESSION")
  (("FIELD" "SESSION:FIELD") "https://shirakumo.github.io/radiance/#SESSION:FIELD" "SESSION:FIELD")
  (("IMPLEMENTATION" "SESSION:IMPLEMENTATION") "https://shirakumo.github.io/radiance/#SESSION:IMPLEMENTATION" "SESSION:IMPLEMENTATION")
  (("TIMEOUT" "SESSION:TIMEOUT") "https://shirakumo.github.io/radiance/#SESSION:TIMEOUT" "SESSION:TIMEOUT")
  (("=" "SESSION:=") "https://shirakumo.github.io/radiance/#SESSION:=" "SESSION:=")
  (("ACTIVE-P" "SESSION:ACTIVE-P") "https://shirakumo.github.io/radiance/#SESSION:ACTIVE-P" "SESSION:ACTIVE-P")
  (("END" "SESSION:END") "https://shirakumo.github.io/radiance/#SESSION:END" "SESSION:END")
  (("GET" "SESSION:GET") "https://shirakumo.github.io/radiance/#SESSION:GET" "SESSION:GET")
  (("ID" "SESSION:ID") "https://shirakumo.github.io/radiance/#SESSION:ID" "SESSION:ID")
  (("LIST" "SESSION:LIST") "https://shirakumo.github.io/radiance/#SESSION:LIST" "SESSION:LIST")
  (("START" "SESSION:START") "https://shirakumo.github.io/radiance/#SESSION:START" "SESSION:START")
  (("*IMPLEMENTATION*" "USER:*IMPLEMENTATION*") "https://shirakumo.github.io/radiance/#USER:*IMPLEMENTATION*" "USER:*IMPLEMENTATION*")
  (("USER" "USER:USER") "https://shirakumo.github.io/radiance/#USER:USER" "USER:USER")
  (("CONDITION" "USER:CONDITION") "https://shirakumo.github.io/radiance/#USER:CONDITION" "USER:CONDITION")
  (("NOT-FOUND" "USER:NOT-FOUND") "https://shirakumo.github.io/radiance/#USER:NOT-FOUND" "USER:NOT-FOUND")
  (("FIELD" "USER:FIELD") "https://shirakumo.github.io/radiance/#USER:FIELD" "USER:FIELD")
  (("IMPLEMENTATION" "USER:IMPLEMENTATION") "https://shirakumo.github.io/radiance/#USER:IMPLEMENTATION" "USER:IMPLEMENTATION")
  (("=" "USER:=") "https://shirakumo.github.io/radiance/#USER:=" "USER:=")
  (("ACTION" "USER:ACTION") "https://shirakumo.github.io/radiance/#USER:ACTION" "USER:ACTION")
  (("ACTIONS" "USER:ACTIONS") "https://shirakumo.github.io/radiance/#USER:ACTIONS" "USER:ACTIONS")
  (("ADD-DEFAULT-PERMISSIONS" "USER:ADD-DEFAULT-PERMISSIONS") "https://shirakumo.github.io/radiance/#USER:ADD-DEFAULT-PERMISSIONS" "USER:ADD-DEFAULT-PERMISSIONS")
  (("CHECK" "USER:CHECK") "https://shirakumo.github.io/radiance/#USER:CHECK" "USER:CHECK")
  (("FIELDS" "USER:FIELDS") "https://shirakumo.github.io/radiance/#USER:FIELDS" "USER:FIELDS")
  (("GET" "USER:GET") "https://shirakumo.github.io/radiance/#USER:GET" "USER:GET")
  (("GRANT" "USER:GRANT") "https://shirakumo.github.io/radiance/#USER:GRANT" "USER:GRANT")
  (("LIST" "USER:LIST") "https://shirakumo.github.io/radiance/#USER:LIST" "USER:LIST")
  (("REMOVE" "USER:REMOVE") "https://shirakumo.github.io/radiance/#USER:REMOVE" "USER:REMOVE")
  (("REMOVE-FIELD" "USER:REMOVE-FIELD") "https://shirakumo.github.io/radiance/#USER:REMOVE-FIELD" "USER:REMOVE-FIELD")
  (("REVOKE" "USER:REVOKE") "https://shirakumo.github.io/radiance/#USER:REVOKE" "USER:REVOKE")
  (("USERNAME" "USER:USERNAME") "https://shirakumo.github.io/radiance/#USER:USERNAME" "USER:USERNAME"))
